#ifndef LIFE_DOCUMENTS_H
#define LIFE_DOCUMENTS_H
#include <math.h>
#include <json-glib/json-glib.h>
#include <glib/gstdio.h>
#include "engine.h"
static int life_entry_order(const void *a,const void *b){const LifeEntry *x=a,*y=b;return x->y==y->y?(x->x>y->x)-(x->x<y->x):(x->y>y->y)-(x->y<y->y);}
static void life_json_points(JsonBuilder *b,const char *key,const LifeMap *m){json_builder_set_member_name(b,key);json_builder_begin_array(b);int n=life_map_count(m);LifeEntry *p=g_new(LifeEntry,n);int k=0;for(size_t i=0;i<m->cap;i++)if(m->entries[i].used&&m->entries[i].value)p[k++]=m->entries[i];if(n>1)qsort(p,(size_t)n,sizeof(LifeEntry),life_entry_order);for(int i=0;i<n;i++){json_builder_begin_array(b);json_builder_add_int_value(b,p[i].x);json_builder_add_int_value(b,p[i].y);json_builder_end_array(b);}g_free(p);json_builder_end_array(b);}
static void life_json_grid(JsonBuilder *b,const char *key,const LifeMap *points,int x0,int y0,int w,int h){json_builder_set_member_name(b,key);json_builder_begin_array(b);for(int y=y0;y<y0+h;y++){json_builder_begin_array(b);for(int x=x0;x<x0+w;x++)json_builder_add_int_value(b,life_map_get(points,x,y)?1:0);json_builder_end_array(b);}json_builder_end_array(b);}
static gchar *life_json(Engine *e){LifeMap live=life_live(e),initial={0};if(e->generation==0||!e->seed.cells)initial=life_map_clone(&live);else{initial=life_map_clone(&e->seed.outside);for(int i=0;i<e->cols*e->rows;i++)if(e->seed.cells[i])life_map_put(&initial,i%e->cols,i/e->cols,1);}int x0=0,y0=0,x1=0,y1=0,w=e->cols,h=e->rows,first=1;if(!e->borders){const LifeMap *maps[]={&live,&initial};for(int n=0;n<2;n++)for(size_t i=0;i<maps[n]->cap;i++)if(maps[n]->entries[i].used&&maps[n]->entries[i].value){LifeEntry p=maps[n]->entries[i];if(first){x0=x1=p.x;y0=y1=p.y;first=0;}else{x0=MIN(x0,p.x);x1=MAX(x1,p.x);y0=MIN(y0,p.y);y1=MAX(y1,p.y);}}w=MAX(5,x1-x0+1);h=MAX(5,y1-y0+1);}int compatible=w<=100&&h<=100;w=MIN(512,w);h=MIN(512,h);JsonBuilder *b=json_builder_new();json_builder_begin_object(b);
#define INT(k,v) json_builder_set_member_name(b,k);json_builder_add_int_value(b,(gint64)(v))
#define STR(k,v) json_builder_set_member_name(b,k);json_builder_add_string_value(b,v)
#define BOOL(k,v) json_builder_set_member_name(b,k);json_builder_add_boolean_value(b,v)
 INT("version",3);STR("app","Conway’s Game of Life Lab");INT("rows",h);INT("cols",w);INT("native_rows",e->rows);INT("native_cols",e->cols);INT("generation",e->generation);json_builder_set_member_name(b,"population_history");json_builder_begin_array(b);for(int i=0;i<e->population_count;i++)json_builder_add_int_value(b,life_population_sample(e,i));json_builder_end_array(b);BOOL("borders",e->borders);BOOL("v2_compatible",compatible);BOOL("wrap",e->wrap);json_builder_set_member_name(b,"speed");json_builder_add_double_value(b,e->speed);STR("name",e->name);life_json_grid(b,"grid",&live,x0,y0,w,h);life_json_grid(b,"generation_zero_grid",&initial,x0,y0,w,h);life_json_points(b,"live_cells",&live);life_json_points(b,"generation_zero_cells",&initial);json_builder_set_member_name(b,"rules");json_builder_begin_object(b);INT("survival_min",e->survival_min);INT("survival_max",e->survival_max);INT("birth_count",e->birth_count);json_builder_end_object(b);json_builder_end_object(b);JsonGenerator *g=json_generator_new();JsonNode *root=json_builder_get_root(b);json_generator_set_root(g,root);json_generator_set_pretty(g,TRUE);gchar *data=json_generator_to_data(g,NULL);json_node_free(root);g_object_unref(g);g_object_unref(b);life_map_free(&live);life_map_free(&initial);return data;
#undef INT
#undef STR
#undef BOOL
}
static uint8_t *life_parse_grid(JsonNode *node,int rows,int cols){if(!JSON_NODE_HOLDS_ARRAY(node))return NULL;JsonArray *grid=json_node_get_array(node);if(json_array_get_length(grid)!=(guint)rows)return NULL;uint8_t *cells=g_malloc0((gsize)rows*cols);for(int y=0;y<rows;y++){JsonNode *rn=json_array_get_element(grid,y);if(!JSON_NODE_HOLDS_ARRAY(rn))goto invalid;JsonArray *row=json_node_get_array(rn);if(json_array_get_length(row)!=(guint)cols)goto invalid;for(int x=0;x<cols;x++){JsonNode *v=json_array_get_element(row,x);if(json_node_get_value_type(v)!=G_TYPE_INT64)goto invalid;gint64 value=json_node_get_int(v);if(value!=0&&value!=1)goto invalid;cells[y*cols+x]=(uint8_t)value;}}return cells;invalid:g_free(cells);return NULL;}
static int life_read_int(JsonObject *o,const char *key,gint64 fallback,gint64 *result){if(!json_object_has_member(o,key)){*result=fallback;return 1;}JsonNode *n=json_object_get_member(o,key);if(json_node_get_value_type(n)!=G_TYPE_INT64)return 0;*result=json_node_get_int(n);return 1;}
static int life_apply_points(Engine *e,JsonNode *node){if(!JSON_NODE_HOLDS_ARRAY(node))return 0;JsonArray *a=json_node_get_array(node);guint n=json_array_get_length(a);if(n>1000000)return 0;for(guint i=0;i<n;i++){JsonNode *row=json_array_get_element(a,i);if(!JSON_NODE_HOLDS_ARRAY(row))return 0;JsonArray *p=json_node_get_array(row);if(json_array_get_length(p)!=2)return 0;JsonNode *x=json_array_get_element(p,0),*y=json_array_get_element(p,1);if(json_node_get_value_type(x)!=G_TYPE_INT64||json_node_get_value_type(y)!=G_TYPE_INT64)return 0;gint64 cx=json_node_get_int(x),cy=json_node_get_int(y);if(cx < -1000000000||cx>1000000000||cy < -1000000000||cy>1000000000)return 0;life_set(e,(int)cx,(int)cy,1);}return 1;}
static int life_load_json(Engine *e,const gchar *data,GError **error){JsonParser *p=json_parser_new();uint8_t *grid=NULL,*start=NULL;Engine fresh,seed;life_init(&fresh);life_init(&seed);int ok=0;if(strlen(data)>16000000){g_set_error_literal(error,G_FILE_ERROR,G_FILE_ERROR_INVAL,"Choose a Life file smaller than 16 MB.");goto done;}if(!json_parser_load_from_data(p,data,-1,error))goto done;JsonNode *root=json_parser_get_root(p);if(!JSON_NODE_HOLDS_OBJECT(root))goto invalid;JsonObject *o=json_node_get_object(root);gint64 rows,cols,nrows,ncols,generation,low=2,high=3,birth=3;if(!life_read_int(o,"rows",0,&rows)||!life_read_int(o,"cols",0,&cols)||rows<4||rows>512||cols<4||cols>512)goto size_error;if(!life_read_int(o,"native_rows",rows,&nrows)||!life_read_int(o,"native_cols",cols,&ncols)||nrows<4||nrows>512||ncols<4||ncols>512)goto size_error;if(!json_object_has_member(o,"grid"))goto invalid;grid=life_parse_grid(json_object_get_member(o,"grid"),(int)rows,(int)cols);if(!grid)goto invalid;start=json_object_has_member(o,"generation_zero_grid")?life_parse_grid(json_object_get_member(o,"generation_zero_grid"),(int)rows,(int)cols):g_memdup2(grid,(gsize)rows*cols);if(!start)goto invalid;if(!life_read_int(o,"generation",0,&generation)||generation<0||generation==G_MAXINT64)goto invalid;double speed=2;if(json_object_has_member(o,"speed")){JsonNode *n=json_object_get_member(o,"speed");GType t=json_node_get_value_type(n);if(t!=G_TYPE_INT64&&t!=G_TYPE_DOUBLE)goto invalid;speed=json_node_get_double(n);if(!isfinite(speed)||speed<.1||speed>60)goto invalid;}int borders=1,wrap=1;const char *bools[]={"borders","wrap"};int *values[]={&borders,&wrap};for(int i=0;i<2;i++)if(json_object_has_member(o,bools[i])){JsonNode *n=json_object_get_member(o,bools[i]);if(json_node_get_value_type(n)!=G_TYPE_BOOLEAN)goto invalid;*values[i]=json_node_get_boolean(n);}if(json_object_has_member(o,"rules")){JsonNode *n=json_object_get_member(o,"rules");if(!JSON_NODE_HOLDS_OBJECT(n))goto invalid;JsonObject *r=json_node_get_object(n);if(!life_read_int(r,"survival_min",2,&low)||!life_read_int(r,"survival_max",3,&high)||!life_read_int(r,"birth_count",3,&birth))goto invalid;}if(low<0||high>8||low>high||birth<0||birth>8||(!borders&&birth==0))goto invalid;
 Engine *both[]={&fresh,&seed};for(int i=0;i<2;i++){Engine *n=both[i];free(n->cells);free(n->selected);n->cols=(int)ncols;n->rows=(int)nrows;n->borders=borders;n->cells=calloc((size_t)ncols*nrows,1);n->selected=calloc((size_t)ncols*nrows,1);}if(json_object_has_member(o,"live_cells")){if(!life_apply_points(&fresh,json_object_get_member(o,"live_cells")))goto invalid;}else for(int y=0;y<rows;y++)for(int x=0;x<cols;x++)life_set(&fresh,x,y,grid[y*cols+x]);if(json_object_has_member(o,"generation_zero_cells")){if(!life_apply_points(&seed,json_object_get_member(o,"generation_zero_cells")))goto invalid;}else for(int y=0;y<rows;y++)for(int x=0;x<cols;x++)life_set(&seed,x,y,start[y*cols+x]);fresh.generation=(uint64_t)generation;fresh.speed=speed;fresh.wrap=wrap;fresh.survival_min=(int)low;fresh.survival_max=(int)high;fresh.birth_count=(int)birth;fresh.cursor_x=fresh.cols/2;fresh.cursor_y=fresh.rows/2;if(json_object_has_member(o,"name")){JsonNode *n=json_object_get_member(o,"name");if(json_node_get_value_type(n)!=G_TYPE_STRING)goto invalid;g_strlcpy(fresh.name,json_node_get_string(n),sizeof(fresh.name));}else strcpy(fresh.name,"Imported canvas");fresh.seed.cells=g_memdup2(seed.cells,(gsize)ncols*nrows);fresh.seed.outside=life_map_clone(&seed.outside);g_strlcpy(fresh.seed.name,fresh.name,sizeof(fresh.seed.name));life_population_reset(&fresh);if(json_object_has_member(o,"population_history")){JsonNode *trend=json_object_get_member(o,"population_history");if(JSON_NODE_HOLDS_ARRAY(trend)){JsonArray *a=json_node_get_array(trend);guint n=json_array_get_length(a);fresh.population_count=0;for(guint i=n>LIFE_POPULATION_LIMIT?n-LIFE_POPULATION_LIMIT:0;i<n;i++){JsonNode *v=json_array_get_element(a,i);if(json_node_get_value_type(v)!=G_TYPE_INT64||json_node_get_int(v)<0||json_node_get_int(v)>INT32_MAX){fresh.population_count=0;break;}fresh.population_history[fresh.population_count++]=(int)json_node_get_int(v);}life_population_sync(&fresh);}}life_destroy(e);*e=fresh;memset(&fresh,0,sizeof(fresh));ok=1;goto done;
size_error:g_set_error_literal(error,G_FILE_ERROR,G_FILE_ERROR_INVAL,"Canvas dimensions are too large. Import a smaller canvas.");goto done;
invalid:g_set_error_literal(error,G_FILE_ERROR,G_FILE_ERROR_INVAL,"Invalid canvas dimensions, rules or cell data.");
done:life_destroy(&fresh);life_destroy(&seed);g_free(grid);g_free(start);g_object_unref(p);return ok;}
static int life_write(Engine *e,const gchar *path,GError **error){gchar *data=life_json(e);gchar *temp=g_strconcat(path,".tmp",NULL);int ok=g_file_set_contents(temp,data,-1,error);if(ok&&g_rename(temp,path)!=0){g_set_error_literal(error,G_FILE_ERROR,G_FILE_ERROR_FAILED,"Could not finish saving the canvas.");ok=0;}g_free(data);g_free(temp);return ok;}
static int life_documents_match(const gchar *current,const gchar *saved){if(!current||!saved)return 0;JsonParser *a=json_parser_new(),*b=json_parser_new();int equal=0;if(json_parser_load_from_data(a,current,-1,NULL)&&json_parser_load_from_data(b,saved,-1,NULL)){JsonNode *x=json_parser_get_root(a),*y=json_parser_get_root(b);if(JSON_NODE_HOLDS_OBJECT(x)&&JSON_NODE_HOLDS_OBJECT(y)){JsonObject *old=json_node_get_object(y);if(!json_object_has_member(old,"population_history")||JSON_NODE_HOLDS_NULL(json_object_get_member(old,"population_history")))json_object_remove_member(json_node_get_object(x),"population_history");equal=json_node_equal(x,y);}}g_object_unref(a);g_object_unref(b);return equal;}

#endif
