#ifndef LIFE_ENGINE_H
#define LIFE_ENGINE_H
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "patterns.h"
#define LIFE_LIMIT 512
#define LIFE_HISTORY 96
#define LIFE_POPULATION_LIMIT 2048
/* Sparse coordinate maps permit negative coordinates and an unbounded viewport. */
typedef struct {int x,y,value,used;} LifeEntry;
typedef struct {LifeEntry *entries;size_t cap,len;} LifeMap;
static uint64_t life_hash(int x,int y){uint64_t z=((uint64_t)(uint32_t)x<<32)|(uint32_t)y;z^=z>>30;z*=UINT64_C(0xbf58476d1ce4e5b9);z^=z>>27;z*=UINT64_C(0x94d049bb133111eb);return z^(z>>31);}
static void life_map_free(LifeMap *m){free(m->entries);memset(m,0,sizeof(*m));}
static LifeEntry *life_map_find(const LifeMap *m,int x,int y){if(!m->cap)return NULL;size_t i=(size_t)life_hash(x,y)&(m->cap-1);while(m->entries[i].used){if(m->entries[i].x==x&&m->entries[i].y==y)return &m->entries[i];i=(i+1)&(m->cap-1);}return NULL;}
static void life_map_put(LifeMap *m,int x,int y,int value);
static void life_map_grow(LifeMap *m){LifeMap old=*m;m->cap=m->cap?m->cap*2:32;m->len=0;m->entries=calloc(m->cap,sizeof(LifeEntry));if(!m->entries)abort();for(size_t i=0;i<old.cap;i++)if(old.entries[i].used)life_map_put(m,old.entries[i].x,old.entries[i].y,old.entries[i].value);free(old.entries);}
static void life_map_put(LifeMap *m,int x,int y,int value){if(!m->cap||(m->len+1)*10>m->cap*7)life_map_grow(m);size_t i=(size_t)life_hash(x,y)&(m->cap-1);while(m->entries[i].used&&(m->entries[i].x!=x||m->entries[i].y!=y))i=(i+1)&(m->cap-1);if(!m->entries[i].used){m->len++;m->entries[i]=(LifeEntry){x,y,value,1};}else m->entries[i].value=value;}
static int life_map_get(const LifeMap *m,int x,int y){LifeEntry *p=life_map_find(m,x,y);return p?p->value:0;}
static int life_map_count(const LifeMap *m){int n=0;for(size_t i=0;i<m->cap;i++)n+=m->entries[i].used&&m->entries[i].value!=0;return n;}
static LifeMap life_map_clone(const LifeMap *m){LifeMap n={0};for(size_t i=0;i<m->cap;i++)if(m->entries[i].used&&m->entries[i].value)life_map_put(&n,m->entries[i].x,m->entries[i].y,m->entries[i].value);return n;}
typedef struct {uint8_t *cells,*initial;uint64_t generation;char name[256];LifeMap outside,initial_outside;int cols,rows,borders,low,high,birth;int *population_history,population_count;} Snapshot;
typedef struct {int cols,rows,wrap,borders,survival_min,survival_max,birth_count,equilibrium;double speed;uint64_t generation;uint8_t *cells,*selected;LifeMap outside,selected_outside;int cursor_x,cursor_y;char name[256];Snapshot history[LIFE_HISTORY],redos[LIFE_HISTORY],seed;int history_count,redo_count;int population_history[LIFE_POPULATION_LIMIT],population_count;} Engine;
static void life_init(Engine *e){memset(e,0,sizeof(*e));e->cols=160;e->rows=100;e->cursor_x=80;e->cursor_y=50;e->wrap=1;e->speed=2;e->survival_min=2;e->survival_max=3;e->birth_count=3;e->cells=calloc(16000,1);e->selected=calloc(16000,1);strcpy(e->name,"Default");e->population_count=1;}
static int life_valid(const Engine *e,int x,int y){return !e->borders||(x>=0&&x<e->cols&&y>=0&&y<e->rows);}
static int life_alive(const Engine *e,int x,int y){if(x>=0&&x<e->cols&&y>=0&&y<e->rows)return e->cells[y*e->cols+x];return !e->borders&&life_map_get(&e->outside,x,y);}
static void life_set(Engine *e,int x,int y,int alive){if(!life_valid(e,x,y))return;if(x>=0&&x<e->cols&&y>=0&&y<e->rows)e->cells[y*e->cols+x]=!!alive;else life_map_put(&e->outside,x,y,!!alive);e->equilibrium=0;}
static LifeMap life_live(const Engine *e){LifeMap n=life_map_clone(&e->outside);for(int i=0;i<e->rows*e->cols;i++)if(e->cells[i])life_map_put(&n,i%e->cols,i/e->cols,1);return n;}
static LifeMap life_selection(const Engine *e){LifeMap n=life_map_clone(&e->selected_outside);for(int i=0;i<e->rows*e->cols;i++)if(e->selected[i])life_map_put(&n,i%e->cols,i/e->cols,1);return n;}
static int life_selection_count(const Engine *e){int n=life_map_count(&e->selected_outside);for(int i=0;i<e->rows*e->cols;i++)n+=e->selected[i];return n;}
static void life_unselect(Engine *e){memset(e->selected,0,(size_t)e->cols*e->rows);life_map_free(&e->selected_outside);}
static void life_select(Engine *e,int x,int y){if(!life_valid(e,x,y))return;if(x>=0&&x<e->cols&&y>=0&&y<e->rows)e->selected[y*e->cols+x]=1;else life_map_put(&e->selected_outside,x,y,1);}
static void life_move_cursor(Engine *e,int dx,int dy,int select){if(select)life_select(e,e->cursor_x,e->cursor_y);e->cursor_x+=dx;e->cursor_y+=dy;if(e->borders){if(e->cursor_x<0)e->cursor_x=0;if(e->cursor_x>=e->cols)e->cursor_x=e->cols-1;if(e->cursor_y<0)e->cursor_y=0;if(e->cursor_y>=e->rows)e->cursor_y=e->rows-1;}if(select)life_select(e,e->cursor_x,e->cursor_y);}
static int life_population(const Engine *e){int n=life_map_count(&e->outside);for(int i=0;i<e->rows*e->cols;i++)n+=e->cells[i];return n;}
static void life_population_reset(Engine *e){e->population_count=1;e->population_history[0]=life_population(e);}
static void life_population_sync(Engine *e){if(!e->population_count)e->population_count=1;e->population_history[e->population_count-1]=life_population(e);}
static int life_population_sample(const Engine *e,int i){return i==e->population_count-1?life_population(e):e->population_history[i];}
static void life_population_append(Engine *e){if(e->population_count==LIFE_POPULATION_LIMIT){memmove(e->population_history,e->population_history+1,sizeof(int)*(LIFE_POPULATION_LIMIT-1));e->population_count--;}e->population_history[e->population_count++]=life_population(e);}
static void life_free_snapshot(Snapshot *s){free(s->population_history);free(s->cells);free(s->initial);life_map_free(&s->outside);life_map_free(&s->initial_outside);memset(s,0,sizeof(*s));}
static Snapshot life_snapshot(const Engine *e){size_t n=(size_t)e->cols*e->rows;Snapshot s={.cells=malloc(n),.initial=malloc(n),.generation=e->generation,.cols=e->cols,.rows=e->rows,.borders=e->borders,.low=e->survival_min,.high=e->survival_max,.birth=e->birth_count};memcpy(s.cells,e->cells,n);memcpy(s.initial,e->generation==0||!e->seed.cells?e->cells:e->seed.cells,n);memcpy(s.name,e->name,sizeof(s.name));s.population_count=e->population_count?e->population_count:1;s.population_history=malloc(sizeof(int)*(size_t)s.population_count);memcpy(s.population_history,e->population_history,sizeof(int)*(size_t)s.population_count);s.population_history[s.population_count-1]=life_population(e);s.outside=life_map_clone(&e->outside);s.initial_outside=life_map_clone(e->generation==0||!e->seed.cells?&e->outside:&e->seed.outside);return s;}
static void life_push(Snapshot *list,int *count,Snapshot s){if(*count==LIFE_HISTORY){life_free_snapshot(&list[0]);memmove(list,list+1,sizeof(Snapshot)*(LIFE_HISTORY-1));(*count)--;}list[(*count)++]=s;}
static void life_clear_redos(Engine *e){for(int i=0;i<e->redo_count;i++)life_free_snapshot(&e->redos[i]);e->redo_count=0;}
static void life_checkpoint(Engine *e){life_clear_redos(e);life_push(e->history,&e->history_count,life_snapshot(e));}
static void life_restore(Engine *e,Snapshot s){free(e->cells);free(e->selected);life_map_free(&e->outside);life_map_free(&e->selected_outside);life_free_snapshot(&e->seed);e->cells=s.cells;e->cols=s.cols;e->rows=s.rows;e->borders=s.borders;e->survival_min=s.low;e->survival_max=s.high;e->birth_count=s.birth;e->selected=calloc((size_t)e->cols*e->rows,1);e->generation=s.generation;e->population_count=s.population_count;if(s.population_count)memcpy(e->population_history,s.population_history,sizeof(int)*(size_t)s.population_count);free(s.population_history);e->outside=s.outside;life_population_sync(e);e->equilibrium=0;e->seed.cells=s.initial;e->seed.outside=s.initial_outside;e->seed.generation=0;memcpy(e->seed.name,s.name,sizeof(e->seed.name));}
static void life_undo(Engine *e){if(!e->history_count)return;life_push(e->redos,&e->redo_count,life_snapshot(e));life_restore(e,e->history[--e->history_count]);}
static void life_redo(Engine *e){if(!e->redo_count)return;life_push(e->history,&e->history_count,life_snapshot(e));life_restore(e,e->redos[--e->redo_count]);}
static void life_back(Engine *e){int i=e->history_count-1;while(i>=0&&e->history[i].generation>=e->generation)i--;if(i<0)return;while(e->history_count>i+1)life_free_snapshot(&e->history[--e->history_count]);life_undo(e);}
static void life_remember(Engine *e){if(e->generation==0)life_population_reset(e);life_free_snapshot(&e->seed);e->seed.cells=malloc((size_t)e->rows*e->cols);memcpy(e->seed.cells,e->cells,(size_t)e->rows*e->cols);e->seed.outside=life_map_clone(&e->outside);e->seed.generation=0;memcpy(e->seed.name,e->name,sizeof(e->seed.name));}
static void life_edit_selection(Engine *e,int mode){life_checkpoint(e);LifeMap points=life_selection(e);if(!life_map_count(&points))life_map_put(&points,e->cursor_x,e->cursor_y,1);for(size_t i=0;i<points.cap;i++)if(points.entries[i].used&&points.entries[i].value){LifeEntry p=points.entries[i];life_set(e,p.x,p.y,mode==2?!life_alive(e,p.x,p.y):mode==1);}life_map_free(&points);if(e->generation==0)life_remember(e);}
static int life_step(Engine *e,int record){if(e->generation==0)life_remember(e);life_population_sync(e);if(record)life_checkpoint(e);LifeMap old=life_live(e),counts={0},next={0};for(size_t i=0;i<old.cap;i++)if(old.entries[i].used&&old.entries[i].value){LifeEntry p=old.entries[i];if(!life_map_find(&counts,p.x,p.y))life_map_put(&counts,p.x,p.y,0);for(int dy=-1;dy<=1;dy++)for(int dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;int x=p.x+dx,y=p.y+dy;if(e->borders&&e->wrap){x=(x+e->cols)%e->cols;y=(y+e->rows)%e->rows;}if(life_valid(e,x,y))life_map_put(&counts,x,y,life_map_get(&counts,x,y)+1);}}if(e->borders&&e->birth_count==0)for(int y=0;y<e->rows;y++)for(int x=0;x<e->cols;x++)if(!life_map_find(&counts,x,y))life_map_put(&counts,x,y,0);for(size_t i=0;i<counts.cap;i++)if(counts.entries[i].used){LifeEntry p=counts.entries[i];int on=life_map_get(&old,p.x,p.y)?p.value>=e->survival_min&&p.value<=e->survival_max:p.value==e->birth_count;if(on)life_map_put(&next,p.x,p.y,1);}int changed=life_map_count(&old)!=life_map_count(&next);if(!changed)for(size_t i=0;i<old.cap;i++)if(old.entries[i].used&&old.entries[i].value&&!life_map_get(&next,old.entries[i].x,old.entries[i].y)){changed=1;break;}memset(e->cells,0,(size_t)e->cols*e->rows);life_map_free(&e->outside);for(size_t i=0;i<next.cap;i++)if(next.entries[i].used)life_set(e,next.entries[i].x,next.entries[i].y,1);e->equilibrium=!changed;e->generation++;life_population_append(e);life_map_free(&old);life_map_free(&counts);life_map_free(&next);return changed;}
static void life_clear(Engine *e){life_checkpoint(e);memset(e->cells,0,(size_t)e->rows*e->cols);life_map_free(&e->outside);life_unselect(e);e->generation=0;e->equilibrium=0;life_free_snapshot(&e->seed);life_population_reset(e);}
static void life_restart(Engine *e){if(!e->seed.cells)return;life_checkpoint(e);memcpy(e->cells,e->seed.cells,(size_t)e->rows*e->cols);life_map_free(&e->outside);e->outside=life_map_clone(&e->seed.outside);e->generation=0;e->equilibrium=0;life_population_reset(e);}
static void life_stamp(Engine *e,const char *const *rows,int height,int x,int y,int overwrite){life_checkpoint(e);int w=0;for(int r=0;r<height;r++){int n=(int)strlen(rows[r]);if(n>w)w=n;}for(int ry=0;ry<height;ry++)for(int rx=0;rows[ry][rx];rx++)if(rows[ry][rx]=='O'||overwrite)life_set(e,x-w/2+rx,y-height/2+ry,rows[ry][rx]=='O');if(e->generation==0)life_remember(e);}
static void life_place(Engine *e,const char *const *rows,int h,int x,int y){life_stamp(e,rows,h,x,y,0);}
static void life_paste(Engine *e,const char *const *rows,int h,int x,int y){life_stamp(e,rows,h,x,y,1);}
static void life_pattern(Engine *e,int index){const Pattern *p=&patterns[index];life_checkpoint(e);memset(e->cells,0,(size_t)e->rows*e->cols);life_map_free(&e->outside);life_unselect(e);e->generation=0;snprintf(e->name,sizeof(e->name),"%s",p->name);int w=0;for(int i=0;i<p->height;i++){int n=(int)strlen(p->rows[i]);if(n>w)w=n;}for(int y=0;y<p->height;y++)for(int x=0;p->rows[y][x];x++)if(p->rows[y][x]=='O')life_set(e,x+(e->cols-w)/2,y+(e->rows-p->height)/2,1);life_remember(e);}
static void life_random_region(Engine *e,double density,int x0,int y0,int w,int h){life_checkpoint(e);memset(e->cells,0,(size_t)e->rows*e->cols);life_map_free(&e->outside);life_unselect(e);e->generation=0;for(int y=y0;y<y0+h;y++)for(int x=x0;x<x0+w;x++)life_set(e,x,y,density>=1.0 || (double)rand()/((double)RAND_MAX+1.0)<density);life_remember(e);}
static void life_random(Engine *e,double density){life_random_region(e,density,0,0,e->cols,e->rows);}
static int life_borders(Engine *e,int on,int w,int h){if(w<5||w>512||h<5||h>512||(!on&&e->birth_count==0))return 0;life_checkpoint(e);LifeMap old=life_live(e);free(e->cells);free(e->selected);life_map_free(&e->outside);life_map_free(&e->selected_outside);e->cols=w;e->rows=h;e->borders=on;e->cells=calloc((size_t)w*h,1);e->selected=calloc((size_t)w*h,1);for(size_t i=0;i<old.cap;i++)if(old.entries[i].used)life_set(e,old.entries[i].x,old.entries[i].y,1);life_map_free(&old);if(on){if(e->cursor_x<0)e->cursor_x=0;if(e->cursor_x>=w)e->cursor_x=w-1;if(e->cursor_y<0)e->cursor_y=0;if(e->cursor_y>=h)e->cursor_y=h-1;}life_remember(e);return 1;}
static int life_rules(Engine *e,int low,int high,int birth){if(low<0||high>8||low>high||birth<0||birth>8||(!e->borders&&birth==0))return 0;life_checkpoint(e);e->survival_min=low;e->survival_max=high;e->birth_count=birth;e->equilibrium=0;return 1;}
static char **life_copy_selection(const Engine *e,int *height){LifeMap p=life_selection(e);if(!life_map_count(&p)){life_map_free(&p);return NULL;}int x0=INT32_MAX,y0=INT32_MAX,x1=INT32_MIN,y1=INT32_MIN;for(size_t i=0;i<p.cap;i++)if(p.entries[i].used){LifeEntry c=p.entries[i];if(c.x<x0)x0=c.x;if(c.x>x1)x1=c.x;if(c.y<y0)y0=c.y;if(c.y>y1)y1=c.y;}int w=x1-x0+1,h=y1-y0+1;if((int64_t)w*h>262144){life_map_free(&p);return NULL;}char **rows=calloc((size_t)h+1,sizeof(char*));for(int y=0;y<h;y++){rows[y]=malloc((size_t)w+1);for(int x=0;x<w;x++)rows[y][x]=life_map_get(&p,x+x0,y+y0)&&life_alive(e,x+x0,y+y0)?'O':'.';rows[y][w]=0;}*height=h;life_map_free(&p);return rows;}
static void life_free_rows(char **rows){if(!rows)return;for(int i=0;rows[i];i++)free(rows[i]);free(rows);}
static void life_forget_history(Engine *e){for(int i=0;i<e->history_count;i++)life_free_snapshot(&e->history[i]);e->history_count=0;life_clear_redos(e);}
static void life_destroy(Engine *e){free(e->cells);free(e->selected);life_map_free(&e->outside);life_map_free(&e->selected_outside);life_free_snapshot(&e->seed);life_forget_history(e);}
#endif
