import Foundation
@main struct EngineTests {
    static func main() throws {
        var e=LifeEngine();e.borders=true;e.loadPattern(patterns[8]);let block=e.cells
        for _ in 0..<10 {e.step(record:false)};precondition(e.cells==block)
        e.loadPattern(patterns[7]);let blinker=e.cells;e.step();precondition(e.cells != blinker);e.step();precondition(e.cells==blinker);e.undo();precondition(e.generation==1);e.undo();precondition(e.generation==0)
        e.loadPattern(patterns[0]);for _ in 0..<4 {e.step(record:false)};precondition(e.population==5 && e.cells[49*160+80]==1)
        e.clear();e.wrap=true;e.set(159,0,true);e.set(0,0,true);e.set(1,0,true);e.step();precondition(e.cells[99*160]==1 && e.cells[0]==1 && e.cells[160]==1);e.undo();e.wrap=false;e.step(record:false);precondition(e.population==0)
        for (index,period) in [(1,3),(6,15)] {e.loadPattern(patterns[index]);let seed=e.cells;for _ in 0..<period {e.step(record:false)};precondition(e.cells==seed)}
        for _ in 0..<120 {e.checkpoint()};precondition(e.history.count==96)
        var reset=LifeEngine(); reset.loadPattern(patterns[0]); reset.set(1,1,true);let initial=reset.cells;reset.step();reset.step();let evolved=reset.cells;var restored=LifeEngine();try restored.load(JSONEncoder().encode(reset.document()));precondition(restored.cells==evolved && restored.generation==2);restored.restart();precondition(restored.generation==0 && restored.cells==initial)
        var edits=LifeEngine();edits.loadPattern(patterns[0]);edits.step();let evolvedGrid=edits.cells;edits.checkpoint();edits.set(1,1,true);edits.undo();precondition(edits.generation==1 && edits.cells==evolvedGrid);edits.checkpoint();edits.set(2,2,true);edits.back();precondition(edits.generation==0 && edits.population==5)
        edits.redo();precondition(edits.generation==1 && edits.cells[2*160+2]==1);edits.undo();edits.checkpoint();edits.set(3,3,true);precondition(edits.redos.isEmpty);edits.borders=true;edits.cursorX=0;edits.cursorY=0;edits.moveCursor(-1,0,select:false);precondition(edits.cursorX==0);edits.moveCursor(1,0,select:true);edits.moveCursor(0,1,select:true);precondition(edits.selected==Set([0,1,161]));edits.clear();edits.undo();precondition(edits.seed != nil)
        edits.clear();edits.selected=Set([0,1,161]);edits.editSelection(1);precondition(edits.population==3);edits.editSelection(2);precondition(edits.population==0);edits.undo();precondition(edits.population==3);edits.redo();precondition(edits.population==0);edits.editSelection(1);edits.editSelection(0);precondition(edits.population==0);edits.selected=[];edits.editSelection(2);precondition(edits.population==1);edits.editSelection(2);precondition(edits.population==0)
        let data=try JSONEncoder().encode(e.document());var copy=LifeEngine();try copy.load(data);precondition(copy.cells==e.cells && copy.generation==e.generation && copy.wrap==e.wrap)
        let bad=Data("{\"rows\":4,\"cols\":4,\"grid\":[],\"generation\":0,\"wrap\":true,\"speed\":12,\"name\":\"invalid\",\"version\":3,\"app\":\"Nithi Life\"}".utf8);do{try copy.load(bad);preconditionFailure("Invalid file accepted")}catch{}
        try data.write(to:URL(fileURLWithPath:CommandLine.arguments[1]))
        if CommandLine.arguments.count > 2 { try copy.load(Data(contentsOf:URL(fileURLWithPath:CommandLine.arguments[2])));precondition(copy.population==12 && copy.generation==15) }

        var overlay=LifeEngine();overlay.set(0,0,true);overlay.place(["O.O"],atX:0,atY:0);precondition(overlay.population==3 && overlay.alive(0,0));overlay.place(["O.O"],atX:0,atY:0,overwrite:true);precondition(overlay.population==2 && !overlay.alive(0,0));overlay.name="Named Chart";overlay.undo();precondition(overlay.population==3 && overlay.name=="Named Chart");overlay.restart();precondition(overlay.name=="Named Chart")
        var infinite=LifeEngine();precondition(!infinite.borders)
        for x in -1...1{infinite.set(x,-1,true)};infinite.step();precondition(infinite.population==3 && infinite.alive(0,-2) && infinite.alive(0,-1) && infinite.alive(0,0));infinite.undo();precondition(infinite.alive(-1,-1) && infinite.generation==0);infinite.redo();precondition(infinite.alive(0,-2) && infinite.generation==1)
        infinite.clear();infinite.place([".O.","..O","OOO"],atX:159,atY:99);let start=infinite.live;for _ in 0..<4{infinite.step()};precondition(infinite.live==Set(start.map{Cell(x:$0.x+1,y:$0.y+1)}));var sparseCopy=LifeEngine();try sparseCopy.load(JSONEncoder().encode(infinite.document()));precondition(sparseCopy.live==infinite.live && sparseCopy.generation==4 && !sparseCopy.borders);sparseCopy.restart();precondition(sparseCopy.live==start)
        try JSONEncoder().encode(infinite.document()).write(to:URL(fileURLWithPath:CommandLine.arguments[1]+".sparse"))
        infinite.clear();infinite.set(-10,-10,true);infinite.set(-9,-10,true);infinite.select(-10,-10);infinite.select(-9,-10);let copied=infinite.copiedRows()!;infinite.set(900,900,true);infinite.place(copied,atX:-40,atY:-50);precondition(infinite.alive(-41,-50) && infinite.alive(-40,-50) && infinite.alive(900,900));infinite.undo();precondition(!infinite.alive(-41,-50) && infinite.alive(900,900));infinite.redo();precondition(infinite.alive(-41,-50));infinite.configureBorders(true,20,20);precondition(infinite.population==0);infinite.undo();precondition(!infinite.borders && infinite.alive(900,900));precondition(infinite.document().v2_compatible==false)
        infinite.clear();infinite.configureBorders(true,5,5);infinite.configureRules(0,0,8);infinite.set(2,2,true);infinite.step();precondition(infinite.alive(2,2) && infinite.equilibrium);infinite.configureRules(2,3,3);infinite.step();precondition(infinite.population==0);infinite.randomize(density:1);precondition(infinite.population==25);infinite.randomize(density:0);precondition(infinite.population==0)
        print("Swift engine: still life, oscillator, glider, wrap, undo, periods, history, JSON validation passed.")

        var graph=LifeEngine();graph.clear();for x in 1...3{graph.set(x,1,true)};graph.set(9,9,true)
assert(graph.populationSeries == [4]);graph.step();assert(graph.populationSeries == [4,3]);graph.checkpoint();graph.set(20,20,true);assert(graph.populationSeries == [4,4]);graph.step();assert(graph.populationSeries == [4,4,3]);graph.undo();assert(graph.populationSeries == [4,4]);graph.undo();assert(graph.populationSeries == [4,3]);graph.redo();assert(graph.populationSeries == [4,4]);graph.redo();assert(graph.populationSeries == [4,4,3]);graph.back();assert(graph.populationSeries == [4,4]);graph.restart();assert(graph.populationSeries == [4]);graph.clear();assert(graph.populationSeries == [0]);graph.undo();assert(graph.populationSeries == [4]);graph.clear();for _ in 0..<2100{graph.step(record:false)};assert(graph.populationSeries.count==2048 && graph.populationSeries.allSatisfy{$0==0});var graphCopy=LifeEngine();try graphCopy.load(JSONEncoder().encode(graph.document()));assert(graphCopy.populationSeries==graph.populationSeries);var legacyGraph=graph.document();legacyGraph.population_history=[9,7,0];try graphCopy.load(JSONEncoder().encode(legacyGraph));assert(graphCopy.populationSeries==[9,7,0]);legacyGraph.population_history=nil;try graphCopy.load(JSONEncoder().encode(legacyGraph));assert(graphCopy.populationSeries==[0]);var withoutGraph=try JSONSerialization.jsonObject(with:JSONEncoder().encode(graph.document())) as! [String:Any];withoutGraph.removeValue(forKey:"population_history");let legacyFingerprint=try JSONSerialization.data(withJSONObject:withoutGraph);let unchangedGraphData=try JSONEncoder().encode(graph.document());assert(lifeDocumentsMatch(unchangedGraphData,legacyFingerprint));graph.set(20,20,true);let editedGraphData=try JSONEncoder().encode(graph.document());assert(!lifeDocumentsMatch(editedGraphData,legacyFingerprint));
print("Swift population graph: edits, Step, Back, Undo/Redo, reset, 2048 bound and v2 field roundtrip passed.")

    }
}
