package land.nithi.life;
import org.json.*;
import java.util.*;
public final class Documents {
 static JSONArray points(Set<LifeEngine.Cell> p)throws JSONException{ArrayList<LifeEngine.Cell> list=new ArrayList<>(p);list.sort((a,b)->a.y==b.y?Integer.compare(a.x,b.x):Integer.compare(a.y,b.y));JSONArray r=new JSONArray();for(LifeEngine.Cell c:list)r.put(new JSONArray().put(c.x).put(c.y));return r;}
 static JSONArray grid(Set<LifeEngine.Cell> p,int x0,int y0,int w,int h){JSONArray r=new JSONArray();for(int y=y0;y<y0+h;y++){JSONArray row=new JSONArray();for(int x=x0;x<x0+w;x++)row.put(p.contains(new LifeEngine.Cell(x,y))?1:0);r.put(row);}return r;}
 public static String save(LifeEngine e)throws JSONException{Set<LifeEngine.Cell> live=e.live(),initial=e.initialLive(),all=new HashSet<>(live);all.addAll(initial);int x0=0,y0=0,w=e.cols,h=e.rows;if(!e.borders){int x1=0,y1=0;boolean first=true;for(LifeEngine.Cell p:all){if(first){x0=x1=p.x;y0=y1=p.y;first=false;}else{x0=Math.min(x0,p.x);x1=Math.max(x1,p.x);y0=Math.min(y0,p.y);y1=Math.max(y1,p.y);}}w=Math.max(5,x1-x0+1);h=Math.max(5,y1-y0+1);}boolean compatible=w<=100&&h<=100;w=Math.min(512,w);h=Math.min(512,h);JSONObject d=new JSONObject();d.put("version",3);d.put("app","Conway’s Game of Life Lab");d.put("rows",h);d.put("cols",w);d.put("native_rows",e.rows);d.put("native_cols",e.cols);d.put("borders",e.borders);d.put("v2_compatible",compatible);d.put("generation",e.generation);JSONArray trend=new JSONArray();for(int value:e.populationSeries())trend.put(value);d.put("population_history",trend);d.put("wrap",e.wrap);d.put("speed",e.speed);d.put("name",e.name);d.put("grid",grid(live,x0,y0,w,h));d.put("generation_zero_grid",grid(initial,x0,y0,w,h));d.put("live_cells",points(live));d.put("generation_zero_cells",points(initial));d.put("rules",new JSONObject().put("survival_min",e.survivalMin).put("survival_max",e.survivalMax).put("birth_count",e.birthCount));return d.toString(2);}
 static byte[] parseGrid(JSONObject d,String key,int w,int h)throws JSONException{JSONArray a=d.getJSONArray(key);if(a.length()!=h)throw new JSONException("Invalid grid rows.");byte[] c=new byte[w*h];for(int y=0;y<h;y++){JSONArray row=a.getJSONArray(y);if(row.length()!=w)throw new JSONException("Invalid grid columns.");for(int x=0;x<w;x++){Object v=row.get(x);if(!(v instanceof Number)||(((Number)v).doubleValue()!=0&&((Number)v).doubleValue()!=1))throw new JSONException("Cells must be 0 or 1.");c[y*w+x]=(byte)((Number)v).intValue();}}return c;}
 static void applyPoints(LifeEngine e,JSONArray p)throws JSONException{if(p.length()>1000000)throw new JSONException("Too many cells.");for(int i=0;i<p.length();i++){JSONArray r=p.getJSONArray(i);if(r.length()!=2)throw new JSONException("Invalid coordinates.");Object vx=r.get(0),vy=r.get(1);if(!(vx instanceof Number)||!(vy instanceof Number)||((Number)vx).doubleValue()!=((Number)vx).intValue()||((Number)vy).doubleValue()!=((Number)vy).intValue())throw new JSONException("Coordinates must be integers.");int x=r.getInt(0),y=r.getInt(1);if(x < -1000000000||x>1000000000||y < -1000000000||y>1000000000)throw new JSONException("Coordinates are too large.");e.set(x,y,true);}}
 public static void load(LifeEngine e,String text)throws JSONException{if(text.length()>16000000)throw new JSONException("Choose a Life file smaller than 16 MB.");JSONObject d=new JSONObject(text);int w=d.getInt("cols"),h=d.getInt("rows"),cols=d.optInt("native_cols",w),rows=d.optInt("native_rows",h);long gen=d.optLong("generation",0);double speed=d.optDouble("speed",2);if(w<4||w>512||h<4||h>512||cols<4||cols>512||rows<4||rows>512||gen<0||gen==Long.MAX_VALUE||!Double.isFinite(speed)||speed<.1||speed>60)throw new JSONException("Invalid canvas dimensions or duration. Import a smaller canvas.");byte[] grid=parseGrid(d,"grid",w,h),initial=d.has("generation_zero_grid")?parseGrid(d,"generation_zero_grid",w,h):grid;JSONObject rules=d.optJSONObject("rules");int low=rules==null?2:rules.optInt("survival_min",2),high=rules==null?3:rules.optInt("survival_max",3),birth=rules==null?3:rules.optInt("birth_count",3);boolean borders=d.optBoolean("borders",true);if(low<0||high>8||low>high||birth<0||birth>8||(!borders&&birth==0))throw new JSONException("Invalid rules.");LifeEngine n=new LifeEngine(),seed=new LifeEngine();for(LifeEngine t:new LifeEngine[]{n,seed}){t.cols=cols;t.rows=rows;t.cells=new byte[cols*rows];t.borders=borders;}if(d.has("live_cells"))applyPoints(n,d.getJSONArray("live_cells"));else for(int y=0;y<h;y++)for(int x=0;x<w;x++)n.set(x,y,grid[y*w+x]==1);if(d.has("generation_zero_cells"))applyPoints(seed,d.getJSONArray("generation_zero_cells"));else for(int y=0;y<h;y++)for(int x=0;x<w;x++)seed.set(x,y,initial[y*w+x]==1);e.cols=cols;e.rows=rows;e.cells=n.cells;e.outside=n.outside;e.generation=gen;e.speed=speed;e.borders=borders;e.wrap=d.optBoolean("wrap",true);e.survivalMin=low;e.survivalMax=high;e.birthCount=birth;e.name=d.optString("name","Imported canvas");e.populationHistory.clear();JSONArray trend=d.optJSONArray("population_history");if(trend!=null)for(int i=Math.max(0,trend.length()-LifeEngine.POPULATION_LIMIT);i<trend.length();i++){Object v=trend.opt(i);if(!(v instanceof Number)||((Number)v).doubleValue()<0||((Number)v).doubleValue()>Integer.MAX_VALUE||((Number)v).doubleValue()!=((Number)v).intValue()){e.populationHistory.clear();break;}e.populationHistory.add(((Number)v).intValue());}e.syncPopulation();e.history.clear();e.redos.clear();e.unselect();e.cursorX=cols/2;e.cursorY=rows/2;e.equilibrium=false;e.seed=new LifeEngine.Snapshot(seed.cells,0,e.name);e.seed.outside=seed.outside;}
 static boolean sameJson(Object a,Object b)throws JSONException{if(a instanceof JSONObject&&b instanceof JSONObject){JSONObject x=(JSONObject)a,y=(JSONObject)b;if(x.length()!=y.length())return false;Iterator<String> keys=x.keys();while(keys.hasNext()){String key=keys.next();if(!y.has(key)||!sameJson(x.get(key),y.get(key)))return false;}return true;}if(a instanceof JSONArray&&b instanceof JSONArray){JSONArray x=(JSONArray)a,y=(JSONArray)b;if(x.length()!=y.length())return false;for(int i=0;i<x.length();i++)if(!sameJson(x.get(i),y.get(i)))return false;return true;}if(a instanceof Number&&b instanceof Number)return ((Number)a).doubleValue()==((Number)b).doubleValue();return Objects.equals(a,b);}
 public static boolean matchesSaved(LifeEngine e,String saved)throws JSONException{JSONObject current=new JSONObject(save(e)),previous=new JSONObject(saved);if(!previous.has("population_history")||previous.isNull("population_history"))current.remove("population_history");return sameJson(current,previous);}

}
