package land.nithi.life;
import java.util.*;
public final class LifeEngine {
 public static final class Cell {public final int x,y;public Cell(int x,int y){this.x=x;this.y=y;}public boolean equals(Object o){return o instanceof Cell&&((Cell)o).x==x&&((Cell)o).y==y;}public int hashCode(){return x*73856093^y*19349663;}}
 public int cols=160,rows=100,cursorX=80,cursorY=50,survivalMin=2,survivalMax=3,birthCount=3;public byte[] cells=new byte[16000];public long generation;public boolean borders=false,wrap=true,equilibrium;public double speed=2;public String name="Default";
 public HashSet<Cell> outside=new HashSet<>(),selectedOutside=new HashSet<>();public final HashSet<Integer> selected=new HashSet<>();
 public static final int POPULATION_LIMIT=2048;public ArrayList<Integer> populationHistory=new ArrayList<>(Collections.singletonList(0));
 public int[] populationSeries(){int n=Math.max(1,populationHistory.size());int[] values=new int[n];for(int i=0;i<n-1;i++)values[i]=populationHistory.get(i);values[n-1]=population();return values;}
 void resetPopulation(){populationHistory.clear();populationHistory.add(population());}
 void syncPopulation(){int[] values=populationSeries();populationHistory.clear();for(int v:values)populationHistory.add(v);}
 void appendPopulation(){populationHistory.add(population());if(populationHistory.size()>POPULATION_LIMIT)populationHistory.remove(0);}
 public static final class Snapshot {public int[] populationHistory;public byte[] cells,initial;public HashSet<Cell> outside=new HashSet<>(),initialOutside=new HashSet<>();public long generation;public String name;public int cols=160,rows=100,low=2,high=3,birth=3;public boolean borders;
  Snapshot(byte[] c,long g,String n){cells=c.clone();generation=g;name=n;}
  Snapshot(LifeEngine e){this(e.cells,e.generation,e.name);initial=(e.generation==0?e.cells:(e.seed==null?e.cells:e.seed.cells)).clone();outside=new HashSet<>(e.outside);initialOutside=new HashSet<>(e.generation==0?e.outside:(e.seed==null?e.outside:e.seed.outside));cols=e.cols;rows=e.rows;borders=e.borders;low=e.survivalMin;high=e.survivalMax;birth=e.birthCount;populationHistory=e.populationSeries();}}
 public Snapshot seed;public final ArrayDeque<Snapshot> history=new ArrayDeque<>(),redos=new ArrayDeque<>();
 public int population(){int n=outside.size();for(byte c:cells)n+=c;return n;}
 public HashSet<Cell> live(){HashSet<Cell> r=new HashSet<>(outside);for(int i=0;i<cells.length;i++)if(cells[i]==1)r.add(new Cell(i%cols,i/cols));return r;}
 public HashSet<Cell> selection(){HashSet<Cell> r=new HashSet<>(selectedOutside);for(int i:selected)r.add(new Cell(i%cols,i/cols));return r;}
 public boolean valid(int x,int y){return !borders||(x>=0&&x<cols&&y>=0&&y<rows);}
 public boolean alive(int x,int y){return x>=0&&x<cols&&y>=0&&y<rows?cells[y*cols+x]==1:!borders&&outside.contains(new Cell(x,y));}
 public void unselect(){selected.clear();selectedOutside.clear();}
 public void select(int x,int y){if(!valid(x,y))return;if(x>=0&&x<cols&&y>=0&&y<rows)selected.add(y*cols+x);else selectedOutside.add(new Cell(x,y));}
 public void checkpoint(){redos.clear();history.addLast(new Snapshot(this));if(history.size()>96)history.removeFirst();}
 void restore(Snapshot s){cols=s.cols;rows=s.rows;borders=s.borders;survivalMin=s.low;survivalMax=s.high;birthCount=s.birth;cells=s.cells.clone();outside=new HashSet<>(s.outside);generation=s.generation;populationHistory.clear();if(s.populationHistory!=null)for(int v:s.populationHistory)populationHistory.add(v);syncPopulation();seed=new Snapshot(s.initial==null?s.cells:s.initial,0,s.name);seed.outside=new HashSet<>(s.initialOutside);unselect();equilibrium=false;}
 public void undo(){if(!history.isEmpty()){redos.addLast(new Snapshot(this));restore(history.removeLast());}}
 public void redo(){if(!redos.isEmpty()){history.addLast(new Snapshot(this));restore(redos.removeLast());}}
 public void back(){Snapshot t=null;for(Iterator<Snapshot> i=history.descendingIterator();i.hasNext();){Snapshot s=i.next();if(s.generation<generation){t=s;break;}}if(t==null)return;while(history.peekLast()!=t)history.removeLast();undo();}
 public void set(int x,int y,boolean value){if(!valid(x,y))return;if(x>=0&&x<cols&&y>=0&&y<rows)cells[y*cols+x]=(byte)(value?1:0);else if(value)outside.add(new Cell(x,y));else outside.remove(new Cell(x,y));equilibrium=false;}
 public void moveCursor(int dx,int dy,boolean select){if(select)select(cursorX,cursorY);cursorX+=dx;cursorY+=dy;if(borders){cursorX=Math.max(0,Math.min(cols-1,cursorX));cursorY=Math.max(0,Math.min(rows-1,cursorY));}if(select)select(cursorX,cursorY);}
 public void editSelection(int mode){checkpoint();HashSet<Cell> p=selection();if(p.isEmpty())p.add(new Cell(cursorX,cursorY));for(Cell c:p)set(c.x,c.y,mode==2?!alive(c.x,c.y):mode==1);if(generation==0)rememberSeed();}
 public String[] copiedRows(){HashSet<Cell> p=selection();if(p.isEmpty())return null;int x0=Integer.MAX_VALUE,y0=x0,x1=Integer.MIN_VALUE,y1=x1;for(Cell c:p){x0=Math.min(x0,c.x);y0=Math.min(y0,c.y);x1=Math.max(x1,c.x);y1=Math.max(y1,c.y);}int w=x1-x0+1,h=y1-y0+1;if((long)w*h>262144)throw new IllegalArgumentException("Select a smaller region to copy.");String[] rows=new String[h];for(int y=0;y<h;y++){StringBuilder r=new StringBuilder();for(int x=0;x<w;x++)r.append(p.contains(new Cell(x+x0,y+y0))&&alive(x+x0,y+y0)?'O':'.');rows[y]=r.toString();}return rows;}
 public void place(String[] p,int x,int y){place(p,x,y,false);}
 public void place(String[] p,int x,int y,boolean overwrite){if(p.length==0)return;checkpoint();int w=0;for(String r:p)w=Math.max(w,r.length());for(int ry=0;ry<p.length;ry++)for(int rx=0;rx<p[ry].length();rx++)if(p[ry].charAt(rx)=='O'||overwrite)set(x-w/2+rx,y-p.length/2+ry,p[ry].charAt(rx)=='O');if(generation==0)rememberSeed();}
 public void configureBorders(boolean on,int width,int height){if(width<5||width>512||height<5||height>512)throw new IllegalArgumentException("Width and height must be 5–512.");if(!on&&birthCount==0)throw new IllegalArgumentException("Birth at zero needs a finite canvas.");checkpoint();HashSet<Cell> old=live();cols=width;rows=height;borders=on;cells=new byte[cols*rows];outside.clear();unselect();for(Cell p:old)set(p.x,p.y,true);if(on){cursorX=Math.max(0,Math.min(cols-1,cursorX));cursorY=Math.max(0,Math.min(rows-1,cursorY));}rememberSeed();}
 public void configureRules(int low,int high,int birth){if(low<0||high>8||low>high||birth<0||birth>8||(!borders&&birth==0))throw new IllegalArgumentException("Use counts 0–8 and minimum ≤ maximum. Birth at zero needs a finite canvas.");checkpoint();survivalMin=low;survivalMax=high;birthCount=birth;equilibrium=false;}
 public void step(boolean record){if(generation==0)rememberSeed();syncPopulation();if(record)checkpoint();HashSet<Cell> old=live();HashMap<Cell,Integer> counts=new HashMap<>();for(Cell p:old){if(!counts.containsKey(p))counts.put(p,0);for(int dy=-1;dy<=1;dy++)for(int dx=-1;dx<=1;dx++){if(dx==0&&dy==0)continue;int x=p.x+dx,y=p.y+dy;if(borders&&wrap){x=(x+cols)%cols;y=(y+rows)%rows;}if(valid(x,y)){Cell k=new Cell(x,y);counts.put(k,counts.getOrDefault(k,0)+1);}}}if(borders&&birthCount==0)for(int y=0;y<rows;y++)for(int x=0;x<cols;x++)counts.putIfAbsent(new Cell(x,y),0);HashSet<Cell> next=new HashSet<>();for(Map.Entry<Cell,Integer> pair:counts.entrySet()){int n=pair.getValue();if(old.contains(pair.getKey())?n>=survivalMin&&n<=survivalMax:n==birthCount)next.add(pair.getKey());}cells=new byte[cols*rows];outside.clear();for(Cell p:next)set(p.x,p.y,true);equilibrium=old.equals(next);generation++;appendPopulation();}
 public void clear(){checkpoint();Arrays.fill(cells,(byte)0);outside.clear();unselect();generation=0;seed=null;equilibrium=false;resetPopulation();}
 public void rememberSeed(){if(generation==0)resetPopulation();seed=new Snapshot(cells,0,name);seed.outside=new HashSet<>(outside);}
 public void restart(){if(seed==null)return;checkpoint();cells=seed.cells.clone();outside=new HashSet<>(seed.outside);generation=0;equilibrium=false;resetPopulation();}
 public void pattern(int index){String[] p=Patterns.DATA[index];checkpoint();Arrays.fill(cells,(byte)0);outside.clear();unselect();generation=0;name=p[0];int w=0;for(int i=3;i<p.length;i++)w=Math.max(w,p[i].length());for(int y=3;y<p.length;y++)for(int x=0;x<p[y].length();x++)if(p[y].charAt(x)=='O')set(x+(cols-w)/2,y-3+(rows-(p.length-3))/2,true);rememberSeed();}
 public void randomize(double density){randomizeRegion(density,0,0,cols,rows);}
 public void randomizeRegion(double density,int x0,int y0,int w,int h){checkpoint();Arrays.fill(cells,(byte)0);outside.clear();unselect();generation=0;Random r=new Random();for(int y=y0;y<y0+h;y++)for(int x=x0;x<x0+w;x++)set(x,y,r.nextDouble()<density);rememberSeed();}
 public HashSet<Cell> initialLive(){HashSet<Cell> r=new HashSet<>(generation==0?outside:(seed==null?outside:seed.outside));byte[] c=generation==0?cells:(seed==null?cells:seed.cells);for(int i=0;i<c.length;i++)if(c[i]==1)r.add(new Cell(i%cols,i/cols));return r;}
}
