package land.nithi.life;
import android.app.*;
import android.os.*;
import android.content.*;
import android.content.res.Configuration;
import android.content.res.ColorStateList;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import android.text.InputType;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.HashMap;
import java.util.ArrayList;
import java.util.List;
import org.json.*;
import android.net.Uri;
import android.provider.DocumentsContract;
import android.database.Cursor;

@android.annotation.SuppressLint("GestureBackNavigation")
public final class MainActivity extends Activity {
    static int INK=Color.rgb(9,17,17),PANEL=Color.rgb(18,26,26),MINT=Color.rgb(115,232,176),TEXT=Color.rgb(227,237,232),MUTED=Color.rgb(140,159,152);
    static int GRID=Color.rgb(35,53,46),CURSOR=Color.rgb(138,180,255),SELECTION=Color.rgb(245,166,35),PREVIEW=Color.rgb(162,242,207);
    String theme="Dark",savedFingerprint="",currentName;boolean tourSeen,allowClose,cursorCentered;String[] pending;String pendingName="";JSONArray tour=new JSONArray(),customPatterns=new JSONArray();Button unselect,savePatternButton;Switch wrapSwitch;int tourIndex;Uri sharedTree;
    final LifeEngine engine=new LifeEngine();
    final Handler handler=new Handler(Looper.getMainLooper());
    boolean running=false,showGrid=true,pan=false;
    int density=25;
    String tool="Paint",message="Ready. Draw cells or choose a pattern.";
    TextView title,stats,status,zoom,tempo,rulesText;
    EditText densityInput;
    Button play,undo,restart,redo,panButton;
    BoardView board;
    PopulationGraph populationGraph;
    LinearLayout root;
    android.graphics.drawable.Drawable tourShade;
    final HashMap<View,String> tourTargets=new HashMap<>();final HashMap<View,Float> tourAlphas=new HashMap<>();
    final HashMap<String,Button> toolButtons=new HashMap<>();
    final Runnable tick=new Runnable(){public void run(){if(!running)return;engine.step(true);message=engine.equilibrium?"Equilibrium reached":"Running.";persist();refresh();if(running)handler.postDelayed(this,Math.max(16,(long)(1000/engine.speed)));}};
    int dp(float n){return Math.round(n*getResources().getDisplayMetrics().density);}
    @Override public void onCreate(Bundle state){super.onCreate(state);engine.pattern(1);engine.name="Default";engine.history.clear();try{File f=new File(getFilesDir(),"canvas.life.json");if(f.exists())Documents.load(engine,read(new FileInputStream(f)));}catch(Exception ignored){}try{JSONObject preferences=new JSONObject(read(new FileInputStream(new File(getFilesDir(),"preferences.json"))));theme=preferences.optString("theme","Dark");tourSeen=preferences.optBoolean("tour_seen",false);}catch(Exception ignored){}applyTheme();try{tour=new JSONArray(read(getAssets().open("tour.json")));}catch(Exception ignored){}try{customPatterns=new JSONArray(read(new FileInputStream(new File(getFilesDir(),"patterns.json"))));}catch(Exception ignored){}String tree=getSharedPreferences("portable_files",MODE_PRIVATE).getString("ConwayLifeLab.dataFolder.v1",null);if(tree!=null)sharedTree=Uri.parse(tree);try{savedFingerprint=Documents.save(engine);JSONObject session=new JSONObject(read(new FileInputStream(new File(getFilesDir(),"session.json"))));savedFingerprint=session.optString("saved",savedFingerprint);currentName=session.optString("name",null);if(currentName!=null&&currentName.isEmpty())currentName=null;}catch(Exception ignored){}build();if(!tourSeen)handler.postDelayed(this::startTour,700);}
    GradientDrawable bg(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    TextView label(String text,int size,int color){TextView v=new TextView(this);v.setText(text);v.setTextColor(color);v.setTextSize(size);v.setFontFeatureSettings("tnum");return v;}
    Button button(String text,Runnable action){Button b=new Button(this);b.setText(text);b.setAllCaps(false);b.setTextColor(TEXT);b.setTextSize(12);b.setMinWidth(0);b.setMinimumWidth(0);b.setMinHeight(dp(42));b.setMinimumHeight(dp(42));b.setPadding(dp(12),dp(6),dp(12),dp(6));b.setBackground(bg(PANEL,8));b.setStateListAnimator(null);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,dp(42));lp.setMargins(dp(3),0,dp(3),0);b.setLayoutParams(lp);b.setOnClickListener(v->action.run());markTour(b,tourAreaFor(text));return b;}
    LinearLayout column(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);return v;}
    LinearLayout row(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.HORIZONTAL);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
    void pad(View v,int n){v.setPadding(dp(n),dp(n),dp(n),dp(n));}
    void loadPortablePatterns(){try{HashMap<String,Uri> files=sharedFiles(".pattern.json");for(String filename:files.keySet()){Uri uri=files.get(filename);String text=uri.getScheme().equals("file")?read(new FileInputStream(uri.getPath())):read(getContentResolver().openInputStream(uri));try{JSONObject item=new JSONObject(text);String name=item.optString("name",filename.replace(".pattern.json",""));boolean exists=false;for(int i=0;i<customPatterns.length();i++)if(name.equals(customPatterns.optJSONObject(i).optString("name")))exists=true;if(exists)continue;JSONArray grid=item.getJSONArray("grid"),rows=new JSONArray();if(grid.length()==0||grid.length()>512)continue;boolean valid=true;for(int y=0;y<grid.length();y++){JSONArray line=grid.getJSONArray(y);if(line.length()==0||line.length()>512){valid=false;break;}StringBuilder row=new StringBuilder();for(int x=0;x<line.length();x++){int cell=line.getInt(x);if(cell!=0&&cell!=1){valid=false;break;}row.append(cell==1?'O':'.');}rows.put(row.toString());}if(valid)customPatterns.put(new JSONObject().put("name",name).put("rows",rows));}catch(JSONException ignored){}}}catch(Exception ignored){}}
    void build(){loadPortablePatterns();
        toolButtons.clear();tourTargets.clear();densityInput=null;root=row();root.setGravity(Gravity.TOP);root.setBackgroundColor(INK);setContentView(root);
        root.setOnApplyWindowInsetsListener((v,insets)->{if(Build.VERSION.SDK_INT>=30){android.graphics.Insets i=insets.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout());v.setPadding(i.left,i.top,i.right,i.bottom);}else v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets;});root.requestApplyInsets();
        boolean wide=getResources().getConfiguration().screenWidthDp>=900;
        if(wide){LinearLayout side=column();side.setBackgroundColor(PANEL);pad(side,18);root.addView(side,new LinearLayout.LayoutParams(dp(238),-1));TextView brand=label("Conway’s Game of Life Lab",14,MINT);brand.setTypeface(null,Typeface.BOLD);LinearLayout brandRow=row();ImageView icon=new ImageView(this);icon.setImageResource(land.nithi.life.R.mipmap.app_icon);brandRow.addView(icon,new LinearLayout.LayoutParams(dp(40),dp(40)));LinearLayout namesBrand=column();namesBrand.setPadding(dp(10),0,0,0);namesBrand.addView(brand);namesBrand.addView(label("v"+BuildConfig.VERSION_NAME+(BuildConfig.DEBUG?" · Testing":""),10,MUTED));brandRow.addView(namesBrand);side.addView(brandRow);TextView caption=label("PATTERN LIBRARY",10,MUTED);caption.setPadding(0,dp(18),0,dp(8));caption.setLetterSpacing(.12f);side.addView(caption);
            ScrollView scroll=new ScrollView(this);if(Build.VERSION.SDK_INT>=29)scroll.setVerticalScrollbarThumbDrawable(bg(MUTED,3));LinearLayout seeds=column();scroll.addView(seeds);markTour(scroll,"Pattern Library");side.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
            for(int i=0;i<Patterns.DATA.length;i++){final int index=i;String[] p=Patterns.DATA[i];LinearLayout card=row();card.setBackground(bg(PANEL,10));pad(card,10);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(62));cp.setMargins(0,0,0,dp(6));seeds.addView(card,cp);card.addView(new SeedView(this,p),new LinearLayout.LayoutParams(dp(42),dp(38)));LinearLayout names=column();names.setPadding(dp(12),0,0,0);names.addView(label(p[0],12,TEXT));names.addView(label(p[1],9,MUTED));card.addView(names);card.setOnClickListener(v->selectPattern(index));card.setContentDescription(p[0]+". "+p[2]);card.setFocusable(true);card.setOnKeyListener((v,key,event)->{if(event.getAction()==KeyEvent.ACTION_UP&&key==KeyEvent.KEYCODE_ENTER){selectPattern(index);return true;}return false;});}
            for(int i=0;i<customPatterns.length();i++){final int index=i;JSONObject item=customPatterns.optJSONObject(i);if(item!=null){JSONArray rows=item.optJSONArray("rows");if(rows==null)continue;String[] pattern=new String[rows.length()+3];pattern[0]=item.optString("name");pattern[1]="Saved";pattern[2]="Place your saved pattern.";for(int y=0;y<rows.length();y++)pattern[y+3]=rows.optString(y);LinearLayout card=row();card.setBackground(bg(PANEL,10));pad(card,10);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(62));cp.setMargins(0,0,0,dp(6));seeds.addView(card,cp);card.addView(new SeedView(this,pattern),new LinearLayout.LayoutParams(dp(42),dp(38)));LinearLayout names=column();names.setPadding(dp(12),0,0,0);names.addView(label(pattern[0],12,TEXT));names.addView(label("Saved",9,MUTED));card.addView(names);card.setOnClickListener(v->selectCustom(index));card.setFocusable(true);card.setContentDescription(pattern[0]+". Saved pattern.");card.setOnKeyListener((v,key,event)->{if(event.getAction()==KeyEvent.ACTION_UP&&key==KeyEvent.KEYCODE_ENTER){selectCustom(index);return true;}return false;});}}
            savePatternButton=button("Save to Pattern Library",this::savePattern);side.addView(savePatternButton,new LinearLayout.LayoutParams(-1,dp(44)));
            LinearLayout densityRow=row();densityRow.addView(label("Random %",11,MUTED));EditText densityInput=this.densityInput=new EditText(this);densityInput.setText(String.valueOf(density));densityInput.setTextColor(TEXT);densityInput.setBackground(bg(INK,6));densityInput.setInputType(InputType.TYPE_CLASS_NUMBER);densityRow.addView(densityInput,new LinearLayout.LayoutParams(dp(64),dp(44)));side.addView(densityRow);side.addView(label("Fills the specified amount of the grid randomly",10,MUTED));densityInput.setOnFocusChangeListener((v,focused)->{if(!focused){try{density=Math.max(0,Math.min(100,Integer.parseInt(densityInput.getText().toString())));}catch(Exception ignored){density=25;}densityInput.setText(String.valueOf(density));}});
            Button random=button("Generate",()->{pause();generate();message="Generated Generation 0.";board.fit(true);refresh();persist();});side.addView(random,new LinearLayout.LayoutParams(-1,dp(44)));
            LinearLayout rulesCard=column();pad(rulesCard,8);rulesCard.setBackground(bg(INK,10));LinearLayout rulesHeading=row();rulesHeading.addView(label("Rules",11,MINT),new LinearLayout.LayoutParams(0,-2,1));Button ruleButton=button("Edit Rules",this::editRules);rulesHeading.addView(ruleButton,new LinearLayout.LayoutParams(-2,dp(34)));rulesCard.addView(rulesHeading);TextView rules=rulesText=label("Birth: 3 neighbors.\nSurvival: 2–3 neighbors.",11,MUTED);rules.setLineSpacing(dp(2),1);rulesCard.addView(rules);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,dp(8),0,dp(8));side.addView(rulesCard,rp);LinearLayout files=row();files.addView(button("Save Canvas",this::saveCanvas));files.addView(button("Load Canvas",this::loadCanvas));side.addView(files);LinearLayout portable=row();portable.addView(button("Import",this::open));portable.addView(button("Export",this::save));side.addView(portable);Spinner themes=new Spinner(this);themes.setBackgroundTintList(ColorStateList.valueOf(TEXT));markTour(themes,"Theme");ArrayAdapter<String> themeAdapter=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_item,new String[]{"Dark","Light","Sepia"}){public View getView(int position,View convert,ViewGroup parent){TextView v=(TextView)super.getView(position,convert,parent);v.setTextColor(TEXT);v.setBackgroundColor(PANEL);return v;}public View getDropDownView(int position,View convert,ViewGroup parent){TextView v=(TextView)super.getDropDownView(position,convert,parent);v.setTextColor(TEXT);v.setBackgroundColor(PANEL);return v;}};themeAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);themes.setAdapter(themeAdapter);themes.setSelection(theme.equals("Light")?1:theme.equals("Sepia")?2:0);themes.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int i,long id){String name=new String[]{"Dark","Light","Sepia"}[i];if(!theme.equals(name)){theme=name;applyTheme();savePreferences();build();}}});LinearLayout themeRow=row();themeRow.addView(themes,new LinearLayout.LayoutParams(0,dp(34),1));themeRow.addView(button("Help",this::startTour),new LinearLayout.LayoutParams(-2,dp(34)));side.addView(themeRow);TextView credit=label("v"+BuildConfig.VERSION_NAME+" · Nithilan Vivek · nithi.land",9,MUTED);credit.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://nithi.land"))));credit.setPadding(0,dp(8),0,0);side.addView(credit);
        }
        LinearLayout main=column();root.addView(main,new LinearLayout.LayoutParams(0,-1,1));
        LinearLayout header=row();if(!wide){header.setOrientation(LinearLayout.VERTICAL);header.setGravity(Gravity.START);}pad(header,18);main.addView(header);LinearLayout heading=column();title=label(engine.name,wide?22:18,TEXT);title.setTypeface(null,Typeface.BOLD);heading.addView(title);heading.addView(label("CONWAY’S GAME OF LIFE",9,MUTED));header.addView(heading,wide?new LinearLayout.LayoutParams(0,-2,1):new LinearLayout.LayoutParams(-1,-2));LinearLayout actions=wide?header:row();if(!wide){HorizontalScrollView actionScroll=new HorizontalScrollView(this);actionScroll.setHorizontalScrollBarEnabled(false);actionScroll.addView(actions);header.addView(actionScroll);actions.setPadding(0,dp(12),0,0);}if(!wide)actions.addView(button("Pattern Library",this::patternDialog));undo=button("Undo",()->{pause();engine.undo();message="Undid the latest change.";refresh();persist();});undo.setContentDescription("Undo");actions.addView(undo);redo=button("Redo",()->{pause();engine.redo();message="Redid the latest change.";refresh();persist();});actions.addView(redo);actions.addView(button("Back",()->{pause();if(engine.generation>0){engine.back();refresh();persist();}}));restart=button("Reset Gen 0",()->{pause();engine.restart();refresh();persist();});restart.setContentDescription("Reset Gen 0");actions.addView(restart);if(wide)actions.addView(button("Help",this::startTour));Button more=button("•••",()->{});if(!wide)markTour(more,"Theme");more.setContentDescription("More actions");more.setOnClickListener(v->{PopupMenu menu=new PopupMenu(this,more);String[] entries={"Generate","Clear","Save Canvas","Load Canvas","Import","Export","Edit Rules","Save to Pattern Library","Theme","Data Folder","Help"};for(String e:entries){android.view.MenuItem item=menu.getMenu().add(e);if(e.equals("Save to Pattern Library"))item.setEnabled(!engine.selection().isEmpty());}menu.setOnMenuItemClickListener(item->{switch(item.getTitle().toString()){case "Generate":pause();generate();board.fit(true);refresh();persist();break;case "Clear":pause();engine.clear();message="Canvas cleared.";refresh();persist();break;case "Save Canvas":saveCanvas();break;case "Load Canvas":loadCanvas();break;case "Import":open();break;case "Export":save();break;case "Edit Rules":editRules();break;case "Save to Pattern Library":savePattern();break;case "Data Folder":chooseFolder();break;case "Theme":themeDialog();break;default:startTour();}return true;});menu.show();});actions.addView(more);
        stats=label("",12,MUTED);stats.setPadding(dp(20),0,dp(20),dp(14));LinearLayout statsRow=row();statsRow.addView(stats,new LinearLayout.LayoutParams(0,-2,1));statsRow.addView(button("Specify Chart Size",this::editBorders));main.addView(statsRow);
        populationGraph=new PopulationGraph();markTour(populationGraph,"Population Graph");LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,dp(80));gp.setMargins(dp(14),0,dp(14),dp(10));main.addView(populationGraph,gp);
        board=new BoardView(this);markTour(board,"Canvas");LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,0,1);bp.setMargins(dp(14),0,dp(14),0);main.addView(board,bp);
        HorizontalScrollView toolsScroll=new HorizontalScrollView(this);toolsScroll.setHorizontalScrollBarEnabled(false);LinearLayout tools=row();pad(tools,10);toolsScroll.addView(tools);main.addView(toolsScroll);for(String t:new String[]{"Paint","Erase"}){Button b=button(t,()->{tool=t;message=t.equals("Move")?"Drag to explore. Scroll or pinch to zoom.":"Drag to "+t.toLowerCase(java.util.Locale.US)+" cells.";refresh();});tools.addView(b);toolButtons.put(t,b);}panButton=button("Pan",()->{pan=!pan;refresh();});tools.addView(panButton);CheckBox grid=new CheckBox(this);grid.setText("Grid");grid.setTextColor(MUTED);grid.setButtonTintList(new ColorStateList(new int[][]{{android.R.attr.state_checked},{}},new int[]{MINT,MUTED}));grid.setChecked(showGrid);grid.setOnCheckedChangeListener((v,checked)->{showGrid=checked;board.invalidate();});tools.addView(grid);unselect=button("Unselect",()->{engine.unselect();pending=null;refresh();});tools.addView(unselect);tools.addView(button("−",()->board.zoomBy(1/1.2f,board.getWidth()/2f,board.getHeight()/2f)));zoom=label("100%",10,MUTED);zoom.setGravity(Gravity.CENTER);tools.addView(zoom,new LinearLayout.LayoutParams(dp(50),-2));tools.addView(button("+",()->board.zoomBy(1.2f,board.getWidth()/2f,board.getHeight()/2f)));tools.addView(button("Fit",()->board.fit(true)));
        HorizontalScrollView transportScroll=new HorizontalScrollView(this);transportScroll.setHorizontalScrollBarEnabled(false);transportScroll.setBackgroundColor(PANEL);LinearLayout transport=row();pad(transport,14);transportScroll.addView(transport);main.addView(transportScroll);play=button("▶  Start",this::toggle);play.setTextColor(INK);play.setBackground(bg(MINT,8));transport.addView(play);Button step=button("Step",()->{pause();engine.step(true);refresh();persist();});step.setContentDescription("Step");transport.addView(step);LinearLayout speedPanel=column();speedPanel.setPadding(dp(16),0,dp(16),0);tempo=label("Duration (seconds) · "+String.format(java.util.Locale.US,"%.2f",1/engine.speed),10,MUTED);speedPanel.addView(tempo);SeekBar seek=new SeekBar(this);seek.setThumbTintList(ColorStateList.valueOf(MINT));seek.setProgressTintList(ColorStateList.valueOf(MINT));seek.setProgressBackgroundTintList(ColorStateList.valueOf(MUTED));seek.setMin(10);seek.setMax(1000);seek.setProgress((int)(100/engine.speed));seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int p,boolean from){engine.speed=100.0/Math.max(10,p);tempo.setText("Duration (seconds) · "+String.format(java.util.Locale.US,"%.2f",1/engine.speed));}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){persist();}});speedPanel.addView(seek,new LinearLayout.LayoutParams(dp(168),dp(28)));transport.addView(speedPanel);Switch wrap=wrapSwitch=new Switch(this);wrap.setThumbTintList(new ColorStateList(new int[][]{{android.R.attr.state_checked},{}},new int[]{MINT,MUTED}));wrap.setTrackTintList(new ColorStateList(new int[][]{{android.R.attr.state_checked},{}},new int[]{(MINT&0xFFFFFF)|0x66000000,(MUTED&0xFFFFFF)|0x66000000}));wrap.setText("Wrap edges  ");wrap.setTextSize(11);wrap.setTextColor(MUTED);wrap.setChecked(engine.wrap);wrap.setOnCheckedChangeListener((v,checked)->{engine.wrap=checked;persist();});transport.addView(wrap);
        status=label(message,11,MUTED);status.setMaxLines(2);status.setPadding(dp(20),dp(10),dp(20),dp(10));main.addView(status);board.post(()->{board.fit(true,true);board.requestFocus();});refresh();
    }
    void selectPattern(int i){pause();pending=Arrays.copyOfRange(Patterns.DATA[i],3,Patterns.DATA[i].length);pendingName=Patterns.DATA[i][0];message="Move the preview and click to place "+pendingName+". Esc cancels.";refresh();}
    void patternDialog(){String[] names=new String[Patterns.DATA.length];for(int i=0;i<names.length;i++)names[i]=Patterns.DATA[i][0]+"  ·  "+Patterns.DATA[i][1];LinearLayout b=column();Dialog d=popup("Pattern Library",b);ScrollView scroll=new ScrollView(this);LinearLayout items=column();for(int i=0;i<names.length;i++){final int index=i;items.addView(button(names[i],()->{selectPattern(index);d.dismiss();}));}scroll.addView(items);b.addView(scroll,new LinearLayout.LayoutParams(-1,dp(320)));b.addView(button("Close",d::dismiss));d.show();}
    void refresh(){if(title==null)return;if(rulesText!=null)rulesText.setText("Birth: "+engine.birthCount+" neighbors.\nSurvival: "+engine.survivalMin+"–"+engine.survivalMax+" neighbors.");for(String t:toolButtons.keySet()){Button b=toolButtons.get(t);boolean selected=t.equals(tool);b.setTextColor(selected?INK:TEXT);b.setBackground(bg(selected?MINT:PANEL,8));}if(panButton!=null){panButton.setTextColor(pan?INK:MINT);GradientDrawable shape=bg(pan?MINT:Color.TRANSPARENT,8);shape.setStroke(dp(1),MINT);panButton.setBackground(shape);}redo.setEnabled(!engine.redos.isEmpty());redo.setAlpha(engine.redos.isEmpty()?.35f:1f);title.setText(engine.name);stats.setText(String.format(java.util.Locale.US,"GENERATION  %,d     Live cells  %,d     Canvas: %s  ·  %s",engine.generation,engine.population(),engine.borders?engine.cols+" × "+engine.rows:"Infinite",running?"Running":"Paused"));if(unselect!=null){unselect.setEnabled(!engine.selection().isEmpty());unselect.setAlpha(engine.selection().isEmpty()?.35f:1f);}if(savePatternButton!=null){savePatternButton.setEnabled(!engine.selection().isEmpty());savePatternButton.setAlpha(engine.selection().isEmpty()?.35f:1f);}if(wrapSwitch!=null)wrapSwitch.setEnabled(engine.borders);play.setText(running?"■  Stop":"▶  Start");undo.setEnabled(!engine.history.isEmpty());undo.setAlpha(engine.history.isEmpty()?.35f:1f);restart.setEnabled(engine.seed!=null);status.setText(message);board.invalidate();if(populationGraph!=null)populationGraph.invalidate();}
    void toggle(){if(running){pause();refresh();return;}running=true;message="Running.";handler.postDelayed(tick,(long)(1000/engine.speed));refresh();}
    void pause(){boolean wasRunning=running;running=false;handler.removeCallbacks(tick);if(wasRunning)message=engine.equilibrium?"Paused · Equilibrium reached":"Paused.";persist();if(status!=null)refresh();}
    void persist(){try{File temp=new File(getFilesDir(),"canvas.tmp");try(FileOutputStream out=new FileOutputStream(temp)){out.write(Documents.save(engine).getBytes(StandardCharsets.UTF_8));out.getFD().sync();}if(!temp.renameTo(new File(getFilesDir(),"canvas.life.json")))throw new IOException("Could not finish saving.");write(new File(getFilesDir(),"session.json"),new JSONObject().put("saved",savedFingerprint).put("name",currentName).toString());}catch(Exception e){message="Could not autosave: "+e.getMessage();}}
    File library(){File f=new File(getFilesDir(),"Conway Game of Life Canvases");if(!f.exists())f.mkdirs();return f;}
    boolean dirty(){try{return !Documents.matchesSaved(engine,savedFingerprint);}catch(Exception e){return true;}}
    void write(File f,String text)throws IOException{File temp=new File(f.getParentFile(),f.getName()+".tmp");try(FileOutputStream out=new FileOutputStream(temp)){out.write(text.getBytes(StandardCharsets.UTF_8));out.getFD().sync();}if(!temp.renameTo(f))throw new IOException("Could not finish saving.");}
    Dialog activeDialog;
    Dialog popup(String title,LinearLayout body){Dialog d=new Dialog(this);LinearLayout content=column();pad(content,24);content.setBackground(bg(PANEL,14));TextView heading=label(title,22,TEXT);heading.setTypeface(null,Typeface.BOLD);content.addView(heading);body.setPadding(0,dp(18),0,0);content.addView(body);activeDialog=d;d.setContentView(content);d.getWindow().setBackgroundDrawable(bg(PANEL,14));d.getWindow().setLayout(Math.min(dp(560),getResources().getDisplayMetrics().widthPixels-dp(40)),-2);return d;}
    EditText input(LinearLayout body,String label,String value){body.addView(label(label,12,MUTED));EditText e=new EditText(this);e.setSingleLine(true);e.setText(value);e.setTextColor(TEXT);e.setBackground(bg(INK,6));e.setPadding(dp(10),dp(8),dp(10),dp(8));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(44));lp.setMargins(0,dp(6),0,dp(12));body.addView(e,lp);return e;}
    void showError(String text){LinearLayout b=column();b.addView(label(text,13,TEXT));Dialog d=popup("Could not complete action",b);b.addView(button("Close",d::dismiss));d.show();}
    void saveCanvas(){saveCanvas(null);}
    void saveCanvas(Runnable complete){pause();if(currentName!=null){LinearLayout b=column();b.addView(label("Overwrite the saved canvas or save a new copy.",13,TEXT));Dialog d=popup("Save changes to "+engine.name+"?",b);b.addView(button("Save to Same Canvas",()->{if(writeCanvas(currentName,engine.name)){d.dismiss();if(complete!=null)complete.run();}}));b.addView(button("Save as New Canvas",()->{d.dismiss();nameCanvas(complete);}));b.addView(button("Cancel",d::dismiss));d.show();}else nameCanvas(complete);}
    void nameCanvas(Runnable complete){LinearLayout b=column();EditText input=input(b,"Name",engine.name);Dialog d=popup("Save Canvas",b);b.addView(button("Save",()->{String name=input.getText().toString().trim();if(name.isEmpty()){showError("Enter a canvas name.");return;}String filename=name.replaceAll("[^\\p{L}\\p{N} _-]","_")+".life.json";try{if(savedCanvases().containsKey(filename)){showError("That name exists. Choose another or load it to overwrite.");return;}}catch(Exception e){showError(e.getMessage());return;}if(writeCanvas(filename,name)){d.dismiss();if(complete!=null)complete.run();}}));b.addView(button("Cancel",d::dismiss));d.show();}
    boolean writeCanvas(String filename,String name){try{engine.name=name;String text=Documents.save(engine);if(sharedTree!=null)writeShared(filename,text);else write(new File(library(),filename),text);currentName=filename;savedFingerprint=text;message="Saved "+name;refresh();persist();return true;}catch(Exception e){showError(e.getMessage());return false;}}
    HashMap<String,Uri> savedCanvases()throws Exception{return sharedFiles(".life.json");}
    HashMap<String,Uri> sharedFiles(String suffix)throws Exception{HashMap<String,Uri> files=new HashMap<>();if(sharedTree==null){File[] entries=library().listFiles((d,n)->suffix==null||n.endsWith(suffix));if(entries!=null)for(File f:entries)files.put(f.getName(),Uri.fromFile(f));return files;}Uri children=DocumentsContract.buildChildDocumentsUriUsingTree(sharedTree,DocumentsContract.getTreeDocumentId(sharedTree));try(Cursor c=getContentResolver().query(children,new String[]{DocumentsContract.Document.COLUMN_DOCUMENT_ID,DocumentsContract.Document.COLUMN_DISPLAY_NAME},null,null,null)){if(c!=null)while(c.moveToNext()){String name=c.getString(1);if(suffix==null||name.endsWith(suffix))files.put(name,DocumentsContract.buildDocumentUriUsingTree(sharedTree,c.getString(0)));}}return files;}
    void writeShared(String filename,String text)throws Exception{Uri uri=sharedFiles(null).get(filename);if(uri==null){Uri parent=DocumentsContract.buildDocumentUriUsingTree(sharedTree,DocumentsContract.getTreeDocumentId(sharedTree));uri=DocumentsContract.createDocument(getContentResolver(),parent,"application/json",filename);}if(uri==null)throw new IOException("Could not create canvas.");try(OutputStream out=getContentResolver().openOutputStream(uri,"wt")){out.write(text.getBytes(StandardCharsets.UTF_8));}}
    void loadCanvas(){pause();Runnable choose=()->{try{HashMap<String,Uri> files=savedCanvases();List<String> names=new ArrayList<>(files.keySet());names.sort(String.CASE_INSENSITIVE_ORDER);LinearLayout b=column();Dialog d=popup("Load Canvas",b);if(names.isEmpty())b.addView(label("No saved canvases yet.",13,MUTED));ScrollView scroll=new ScrollView(this);LinearLayout list=column();scroll.addView(list);b.addView(scroll,new LinearLayout.LayoutParams(-1,Math.min(dp(300),dp(46)*Math.max(1,names.size()))));for(String filename:names)list.addView(button(filename.replace(".life.json",""),()->{try{Uri uri=files.get(filename);String text=uri.getScheme().equals("file")?read(new FileInputStream(uri.getPath())):read(getContentResolver().openInputStream(uri));Documents.load(engine,text);currentName=filename;savedFingerprint=Documents.save(engine);pending=null;message="Loaded "+filename;d.dismiss();build();persist();}catch(Exception e){showError(e.getMessage());}}));b.addView(button("Cancel",d::dismiss));d.show();}catch(Exception e){showError(e.getMessage());}};if(dirty())confirmUnsaved(choose);else choose.run();}
    void confirmUnsaved(Runnable continuation){pause();LinearLayout b=column();b.addView(label("Your current canvas has unsaved changes.",13,TEXT));Dialog d=popup("Save your canvas changes?",b);b.addView(button("Save",()->{d.dismiss();saveCanvas(continuation);}));b.addView(button("Discard",()->{d.dismiss();continuation.run();}));b.addView(button("Cancel",d::dismiss));d.show();}
    void chooseFolder(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION|Intent.FLAG_GRANT_PREFIX_URI_PERMISSION);startActivityForResult(i,3);}
    void open(){pause();if(dirty()){confirmUnsaved(this::importFile);return;}importFile();}
    void importFile(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");startActivityForResult(i,1);}
    void save(){pause();try{if(!new JSONObject(Documents.save(engine)).optBoolean("v2_compatible",true)){showError("This canvas exceeds 100 × 100. Please choose a smaller canvas. Save Canvas keeps the whole canvas locally.");return;}}catch(Exception error){showError(error.getMessage());return;}Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,engine.name+".life.json");startActivityForResult(i,2);}
    String read(InputStream stream)throws IOException{try(InputStream in=stream;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))!=-1){if(out.size()+n>16_000_000)throw new IOException("Choose a Life file smaller than 16 MB.");out.write(buffer,0,n);}return out.toString("UTF-8");}}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;try{if(request==3){sharedTree=data.getData();int grants=0;if((data.getFlags()&Intent.FLAG_GRANT_READ_URI_PERMISSION)!=0)grants|=Intent.FLAG_GRANT_READ_URI_PERMISSION;if((data.getFlags()&Intent.FLAG_GRANT_WRITE_URI_PERMISSION)!=0)grants|=Intent.FLAG_GRANT_WRITE_URI_PERMISSION;getContentResolver().takePersistableUriPermission(sharedTree,grants);getSharedPreferences("portable_files",MODE_PRIVATE).edit().putString("ConwayLifeLab.dataFolder.v1",sharedTree.toString()).apply();message="Using shared canvas folder.";refresh();return;}if(request==1){String json=read(getContentResolver().openInputStream(data.getData()));JSONObject document=new JSONObject(json);if(document.optInt("rows")>100||document.optInt("cols")>100)throw new IOException("This canvas exceeds 100 × 100. Please import a smaller canvas.");Documents.load(engine,json);currentName=null;savedFingerprint=Documents.save(engine);message="Canvas loaded.";build();persist();}else if(request==2){try(OutputStream out=getContentResolver().openOutputStream(data.getData(),"wt")){out.write(Documents.save(engine).getBytes(StandardCharsets.UTF_8));}message="Canvas saved.";}refresh();}catch(Exception e){showError(e.getMessage());}}
    @Override protected void onPause(){super.onPause();pause();refresh();}
    @Override public void onConfigurationChanged(Configuration c){super.onConfigurationChanged(c);build();}
    void editSelected(int mode){pause();engine.editSelection(mode);message=mode==0?"Made selected cells dead.":mode==1?"Made selected cells alive.":"Inverted selected cells.";board.keyboardCursor=true;refresh();persist();}
    @Override public boolean dispatchKeyEvent(KeyEvent e){if(getCurrentFocus() instanceof EditText)return super.dispatchKeyEvent(e);if(e.getAction()==KeyEvent.ACTION_DOWN){int k=e.getKeyCode();if(k==KeyEvent.KEYCODE_DPAD_LEFT||k==KeyEvent.KEYCODE_DPAD_RIGHT||k==KeyEvent.KEYCODE_DPAD_UP||k==KeyEvent.KEYCODE_DPAD_DOWN){board.navigate(k==KeyEvent.KEYCODE_DPAD_LEFT?-1:k==KeyEvent.KEYCODE_DPAD_RIGHT?1:0,k==KeyEvent.KEYCODE_DPAD_UP?-1:k==KeyEvent.KEYCODE_DPAD_DOWN?1:0,e.isShiftPressed());return true;}if(e.getRepeatCount()!=0)return super.dispatchKeyEvent(e);boolean ctrl=e.isCtrlPressed()||e.isMetaPressed();switch(e.getKeyCode()){case KeyEvent.KEYCODE_SPACE:editSelected(2);return true;case KeyEvent.KEYCODE_PERIOD:pause();engine.step(true);refresh();persist();return true;case KeyEvent.KEYCODE_B:tool="Paint";refresh();return true;case KeyEvent.KEYCODE_E:tool="Erase";refresh();return true;case KeyEvent.KEYCODE_H:pan=!pan;refresh();return true;case KeyEvent.KEYCODE_F:board.fit(true);return true;case KeyEvent.KEYCODE_PLUS:case KeyEvent.KEYCODE_EQUALS:board.zoomBy(1.2f,board.getWidth()/2f,board.getHeight()/2f);return true;case KeyEvent.KEYCODE_MINUS:board.zoomBy(1/1.2f,board.getWidth()/2f,board.getHeight()/2f);return true;case KeyEvent.KEYCODE_ESCAPE:engine.unselect();pending=null;board.keyboardCursor=true;refresh();return true;case KeyEvent.KEYCODE_ENTER:case KeyEvent.KEYCODE_NUMPAD_ENTER:editSelected(1);return true;case KeyEvent.KEYCODE_DEL:case KeyEvent.KEYCODE_FORWARD_DEL:editSelected(0);return true;case KeyEvent.KEYCODE_C:if(ctrl){copySelection();return true;}break;case KeyEvent.KEYCODE_V:if(ctrl){pasteSelection();return true;}break;case KeyEvent.KEYCODE_R:if(ctrl){pause();engine.restart();refresh();persist();return true;}break;case KeyEvent.KEYCODE_Y:if(ctrl){pause();engine.redo();refresh();persist();return true;}break;case KeyEvent.KEYCODE_Z:if(ctrl){pause();engine.undo();message="Undid the latest change.";refresh();persist();return true;}break;case KeyEvent.KEYCODE_S:if(ctrl){saveCanvas();return true;}break;case KeyEvent.KEYCODE_O:if(ctrl){loadCanvas();return true;}break;}}return super.dispatchKeyEvent(e);}
    void applyTheme(){int[] p=theme.equals("Light")?new int[]{0xFFFFFF,0xF0F0F0,0,0,0x555555,0x000000,0x0000FF,0xFF9F1C,0x68D391}:theme.equals("Sepia")?new int[]{0xF5EAD3,0xEAD8B8,0x5A351D,0x4B2D18,0x6D4A28,0x5A351D,0x8A5A2B,0xB66A2A,0x9D6B36}:new int[]{0x091111,0x121A1A,0x73E8B0,0xE3EDE8,0x8C9F98,0x73E8B0,0x8AB4FF,0xF5A623,0xA2F2CF};INK=p[0]|0xFF000000;PANEL=p[1]|0xFF000000;MINT=p[2]|0xFF000000;TEXT=p[3]|0xFF000000;MUTED=p[4]|0xFF000000;GRID=p[5]|0xFF000000;CURSOR=p[6]|0xFF000000;SELECTION=p[7]|0xFF000000;PREVIEW=p[8]|0xFF000000;getWindow().setStatusBarColor(INK);getWindow().setNavigationBarColor(INK);}
    void savePreferences(){try{String text=new JSONObject().put("theme",theme).put("tour_seen",tourSeen).toString();write(new File(getFilesDir(),"preferences.json"),text);if(sharedTree!=null)writeShared("preferences.json",text);else write(new File(library(),"preferences.json"),text);}catch(Exception e){message=e.getMessage();}}
    String tourAreaFor(String name){switch(name){case "Specify Chart Size":return "Specify Chart Size";case "Paint":case "Erase":case "Pan":return "Tools";case "Fit":return "Fit";case "Unselect":return "Unselect";case "Save to Pattern Library":return "Save to Pattern Library";case "▶  Start":case "Start":case "Step":return "Start";case "Undo":case "Redo":case "Back":case "Reset Gen 0":case "Clear":return "Undo";case "Generate":return "Generate";case "Edit Rules":return "Edit Rules";case "Save Canvas":case "Load Canvas":return "Save Canvas";case "Import":case "Export":return "Export";case "Help":return "Help";default:return "";}}
    void markTour(View target,String area){if(!area.isEmpty())tourTargets.put(target,area);}
    void clearTourHighlight(){if(tourShade!=null){root.getOverlay().remove(tourShade);tourShade=null;}for(View v:tourAlphas.keySet()){v.setForeground(null);v.setAlpha(tourAlphas.get(v));}tourAlphas.clear();}
    void highlightTour(String area){clearTourHighlight();final List<View> targets=new ArrayList<>();for(View v:tourTargets.keySet())if(tourTargets.get(v).equals(area)){tourAlphas.put(v,v.getAlpha());targets.add(v);GradientDrawable focus=bg(Color.TRANSPARENT,8);focus.setStroke(dp(2),MINT);v.setForeground(focus);v.setAlpha(1);}
        tourShade=new android.graphics.drawable.Drawable(){
            public void draw(Canvas canvas){Path shade=new Path();shade.setFillType(Path.FillType.EVEN_ODD);shade.addRect(0,0,root.getWidth(),root.getHeight(),Path.Direction.CW);int[] base=new int[2];root.getLocationInWindow(base);for(View target:targets){if(!target.isShown())continue;android.graphics.Rect visible=new android.graphics.Rect();if(!target.getGlobalVisibleRect(visible))continue;visible.offset(-base[0],-base[1]);shade.addRoundRect(new RectF(visible),dp(8),dp(8),Path.Direction.CW);}Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);paint.setColor(Color.argb(153,0,0,0));canvas.drawPath(shade,paint);}
            public void setAlpha(int alpha){}public void setColorFilter(ColorFilter filter){}public int getOpacity(){return PixelFormat.TRANSLUCENT;}
        };tourShade.setBounds(0,0,root.getWidth(),root.getHeight());root.getOverlay().add(tourShade);
    }
    void startTour(){pause();tourIndex=0;showTour();}
    void showTour(){if(tour.length()==0)return;JSONObject step=tour.optJSONObject(tourIndex);LinearLayout b=column();b.addView(label("GUIDED TOUR · "+(tourIndex+1)+" / "+tour.length(),11,MUTED));TextView text=label(step.optString("text").replace("{MOD}","Ctrl"),14,TEXT);text.setLineSpacing(dp(4),1);b.addView(text);Dialog d=popup(step.optString("title"),b);LinearLayout buttons=row();buttons.addView(button("Skip",()->{tourSeen=true;savePreferences();clearTourHighlight();d.dismiss();}));if(tourIndex>0)buttons.addView(button("Back",()->{tourIndex--;clearTourHighlight();d.dismiss();showTour();}));buttons.addView(button(tourIndex==tour.length()-1?"Finish":"Next",()->{clearTourHighlight();d.dismiss();if(tourIndex==tour.length()-1){tourSeen=true;savePreferences();}else{tourIndex++;showTour();}}));b.addView(buttons);d.setOnCancelListener(v->{tourSeen=true;savePreferences();});highlightTour(step.optString("area"));final android.graphics.drawable.Drawable stepShade=tourShade;d.setOnDismissListener(v->{if(tourShade==stepShade)clearTourHighlight();});d.show();d.getWindow().setDimAmount(0);}
    void themeDialog(){LinearLayout b=column();Dialog d=popup("Theme",b);for(String t:new String[]{"Dark","Light","Sepia"})b.addView(button(t,()->{theme=t;applyTheme();savePreferences();d.dismiss();build();}));d.show();}
    void selectCustom(int i){JSONObject p=customPatterns.optJSONObject(i);JSONArray r=p.optJSONArray("rows");if(r==null)return;pending=new String[r.length()];for(int y=0;y<r.length();y++)pending[y]=r.optString(y);pendingName=p.optString("name");pause();message="Move the preview and click to place "+pendingName;refresh();}
    void savePattern(){String[] rows=engine.copiedRows();if(rows==null)return;LinearLayout b=column();EditText name=input(b,"Pattern name","My pattern");Dialog d=popup("Save to Pattern Library",b);b.addView(button("Save",()->{String n=name.getText().toString().trim();if(n.isEmpty()){showError("Enter a name.");return;}try{for(int i=0;i<customPatterns.length();i++)if(n.equals(customPatterns.getJSONObject(i).optString("name"))){showError("That pattern name exists.");return;}customPatterns.put(new JSONObject().put("name",n).put("rows",new JSONArray(Arrays.asList(rows))));write(new File(getFilesDir(),"patterns.json"),customPatterns.toString());JSONArray grid=new JSONArray();for(String row:rows){JSONArray cells=new JSONArray();for(int x=0;x<row.length();x++)cells.put(row.charAt(x)=='O'?1:0);grid.put(cells);}JSONObject portable=new JSONObject().put("type","pattern").put("version",1).put("name",n).put("rows",rows.length).put("cols",rows[0].length()).put("grid",grid);String filename=n.replaceAll("[^\\p{L}\\p{N} _-]","_")+".pattern.json";if(sharedTree!=null)writeShared(filename,portable.toString());else write(new File(library(),filename),portable.toString());d.dismiss();build();}catch(Exception e){showError(e.getMessage());}}));b.addView(button("Cancel",d::dismiss));d.show();}
    void copySelection(){String[] rows=engine.copiedRows();if(rows==null)return;android.content.ClipboardManager c=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);c.setPrimaryClip(ClipData.newPlainText("Life selection","life-pattern:"+new JSONArray(Arrays.asList(rows))));message="Copied selection.";refresh();}
    void pasteSelection(){try{android.content.ClipboardManager c=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(!c.hasPrimaryClip()){message="Copy a Life selection first.";refresh();return;}String text=c.getPrimaryClip().getItemAt(0).coerceToText(this).toString();if(!text.startsWith("life-pattern:"))return;JSONArray a=new JSONArray(text.substring(13));if(a.length()==0||a.length()>512)return;String[] rows=new String[a.length()];for(int i=0;i<rows.length;i++){rows[i]=a.getString(i);if(rows[i].length()>512||!rows[i].matches("[O.]*"))return;}pause();engine.place(rows,engine.cursorX,engine.cursorY,true);message="Pasted at the cursor.";refresh();persist();}catch(Exception e){showError(e.getMessage());}}
    void generate(){if(densityInput!=null){try{density=Math.max(0,Math.min(100,Integer.parseInt(densityInput.getText().toString())));}catch(NumberFormatException ignored){density=25;}densityInput.setText(String.valueOf(density));}if(engine.borders)engine.randomize(density/100.0);else{int[] r=board.visibleRegion();engine.randomizeRegion(density/100.0,r[0],r[1],r[2],r[3]);}}
    void editRules(){pause();LinearLayout b=column();EditText low=input(b,"Survival minimum",String.valueOf(engine.survivalMin)),high=input(b,"Survival maximum",String.valueOf(engine.survivalMax)),birth=input(b,"Birth count",String.valueOf(engine.birthCount));b.addView(label("Counts 0–8. Birth at zero requires a finite canvas.",11,MUTED));Dialog d=popup("Edit Rules",b);b.addView(button("Reset to Classic Conway",()->{low.setText("2");high.setText("3");birth.setText("3");}));b.addView(button("Apply",()->{try{engine.configureRules(Integer.parseInt(low.getText().toString()),Integer.parseInt(high.getText().toString()),Integer.parseInt(birth.getText().toString()));d.dismiss();refresh();persist();}catch(Exception e){showError(e.getMessage());}}));b.addView(button("Cancel",d::dismiss));d.show();}
    void editBorders(){pause();LinearLayout b=column();EditText width=input(b,"Width (columns)",String.valueOf(engine.cols)),height=input(b,"Height (rows)",String.valueOf(engine.rows));b.addView(label("Choose 5–512. Outside cells are removed; Undo restores them.",11,MUTED));Dialog d=popup("Specify Chart Size",b);b.addView(button("Apply",()->{try{engine.configureBorders(true,Integer.parseInt(width.getText().toString()),Integer.parseInt(height.getText().toString()));d.dismiss();refresh();board.fit(true);persist();}catch(Exception e){showError(e.getMessage());}}));b.addView(button("Infinite",()->{try{engine.configureBorders(false,engine.cols,engine.rows);d.dismiss();refresh();board.fit(true);persist();}catch(Exception e){showError(e.getMessage());}}));b.addView(button("Cancel",()->{d.dismiss();refresh();}));d.show();}
    @Override public void onBackPressed(){if(allowClose||!dirty()){super.onBackPressed();return;}confirmUnsaved(()->{allowClose=true;finish();});}
    final class SeedView extends View {final String[] p;final Paint brush=new Paint(3);SeedView(Context c,String[] pattern){super(c);p=pattern;}protected void onDraw(Canvas c){int w=1;for(int i=3;i<p.length;i++)w=Math.max(w,p[i].length());float s=Math.min(getWidth()/(float)w,getHeight()/(float)(p.length-3));brush.setColor(MINT);for(int y=3;y<p.length;y++)for(int x=0;x<p[y].length();x++)if(p[y].charAt(x)=='O')c.drawRect((getWidth()-w*s)/2+x*s,(getHeight()-(p.length-3)*s)/2+(y-3)*s,(getWidth()-w*s)/2+x*s+Math.max(1,s-1),(getHeight()-(p.length-3)*s)/2+(y-3)*s+Math.max(1,s-1),brush);}}
    final class PopulationGraph extends View {
        final Paint brush=new Paint(Paint.ANTI_ALIAS_FLAG);final Path line=new Path();
        PopulationGraph(){super(MainActivity.this);setContentDescription("Live cells over time");setFocusable(false);}
        @Override protected void onDraw(Canvas c){super.onDraw(c);brush.setStyle(Paint.Style.FILL);brush.setColor(PANEL);c.drawRoundRect(0,0,getWidth(),getHeight(),dp(12),dp(12),brush);brush.setColor(MUTED);brush.setTextSize(dp(11));c.drawText("Live cells over time",dp(12),dp(20),brush);
            int[] samples=engine.populationSeries();int maximum=1;for(int v:samples)maximum=Math.max(maximum,v);double ceiling=Math.max(1,maximum*1.12);float x=0,y=0;line.reset();
            for(int i=0;i<samples.length;i++){x=dp(15)+i/(float)Math.max(1,samples.length-1)*Math.max(1,getWidth()-dp(30));y=dp(32)+(float)(1-samples[i]/ceiling)*Math.max(1,getHeight()-dp(41));if(i==0)line.moveTo(x,y);else line.lineTo(x,y);}
            brush.setColor(MINT);brush.setStyle(Paint.Style.STROKE);brush.setStrokeWidth(dp(2));brush.setStrokeCap(Paint.Cap.ROUND);brush.setStrokeJoin(Paint.Join.ROUND);c.drawPath(line,brush);brush.setStyle(Paint.Style.FILL);c.drawCircle(x,y,dp(3),brush);
        }
    }
    final class BoardView extends View {
        final Paint brush=new Paint(3);final ScaleGestureDetector pinch;float scale=dp(12),ox=0,oy=0,lastX,lastY;int lastCX,lastCY,pointerX=80,pointerY=50;boolean placed=false;boolean hasLast=false,panning=false,multiple=false,selecting=false,keyboardCursor=true;
        BoardView(Context c){super(c);setDefaultFocusHighlightEnabled(false);setFocusable(true);setContentDescription("Canvas. Drag to paint. Use Pan to pan, pinch or scroll to zoom.");pinch=new ScaleGestureDetector(c,new ScaleGestureDetector.SimpleOnScaleGestureListener(){public boolean onScale(ScaleGestureDetector d){zoomBy(d.getScaleFactor(),d.getFocusX(),d.getFocusY());return true;}});}
        void fit(boolean living){fit(living,false);}
        void fit(boolean living,boolean defaultZoom){int x0=0,y0=0,x1=engine.cols-1,y1=engine.rows-1;if(living&&engine.population()>0){x0=y0=Integer.MAX_VALUE;x1=y1=Integer.MIN_VALUE;for(LifeEngine.Cell p:engine.live()){x0=Math.min(x0,p.x);x1=Math.max(x1,p.x);y0=Math.min(y0,p.y);y1=Math.max(y1,p.y);}x0-=8;y0-=8;x1+=8;y1+=8;}scale=defaultZoom?dp(12):Math.max(dp(2),Math.min(dp(28),Math.min(getWidth()/(float)(x1-x0+1),getHeight()/(float)(y1-y0+1))));ox=getWidth()/2f-(x0+x1+1)/2f*scale;oy=getHeight()/2f-(y0+y1+1)/2f*scale;if(!cursorCentered&&getWidth()>0&&getHeight()>0){engine.cursorX=(int)Math.floor((getWidth()/2f-ox)/scale);engine.cursorY=(int)Math.floor((getHeight()/2f-oy)/scale);pointerX=engine.cursorX;pointerY=engine.cursorY;cursorCentered=true;}updateZoom();invalidate();}
        void updateZoom(){if(zoom!=null)zoom.setText((int)(scale/dp(12)*100)+"%");}
        void zoomBy(float f,float x,float y){float next=Math.max(dp(2),Math.min(dp(48),scale*f));f=next/scale;ox=x-(x-ox)*f;oy=y-(y-oy)*f;scale=next;updateZoom();invalidate();}
        protected void onSizeChanged(int w,int h,int ow,int oh){if(ow>0){ox+=(w-ow)/2f;oy+=(h-oh)/2f;}super.onSizeChanged(w,h,ow,oh);}
        int[] visibleRegion(){return new int[]{(int)Math.floor(-ox/scale),(int)Math.floor(-oy/scale),Math.max(1,(int)Math.ceil(getWidth()/scale)),Math.max(1,(int)Math.ceil(getHeight()/scale))};}
        void pointer(float x,float y){int cx=(int)Math.floor((x-ox)/scale),cy=(int)Math.floor((y-oy)/scale);if(engine.valid(cx,cy)){pointerX=cx;pointerY=cy;}invalidate();}
        protected void onDraw(Canvas c){c.drawColor(INK);int[] r=visibleRegion();int x0=engine.borders?Math.max(0,r[0]):r[0],y0=engine.borders?Math.max(0,r[1]):r[1],x1=engine.borders?Math.min(engine.cols,r[0]+r[2]+1):r[0]+r[2]+1,y1=engine.borders?Math.min(engine.rows,r[1]+r[3]+1):r[1]+r[3]+1;if(showGrid&&scale>=dp(5)){brush.setColor(GRID);brush.setStrokeWidth(1);for(int x=x0;x<=x1;x++)c.drawLine(ox+x*scale,engine.borders?Math.max(0,oy):0,ox+x*scale,engine.borders?Math.min(getHeight(),oy+engine.rows*scale):getHeight(),brush);for(int y=y0;y<=y1;y++)c.drawLine(engine.borders?Math.max(0,ox):0,oy+y*scale,engine.borders?Math.min(getWidth(),ox+engine.cols*scale):getWidth(),oy+y*scale,brush);}brush.setColor(MINT);float inset=scale>=dp(6)?dp(1):0;for(LifeEngine.Cell p:engine.live()){float x=ox+p.x*scale,y=oy+p.y*scale;if(x+scale>=0&&y+scale>=0&&x<=getWidth()&&y<=getHeight())c.drawRect(x+inset,y+inset,x+scale-inset,y+scale-inset,brush);}brush.setColor(SELECTION);brush.setAlpha(80);for(LifeEngine.Cell p:engine.selection())c.drawRect(ox+p.x*scale,oy+p.y*scale,ox+(p.x+1)*scale,oy+(p.y+1)*scale,brush);brush.setAlpha(255);if(pending!=null){int w=0;for(String row:pending)w=Math.max(w,row.length());brush.setColor(PREVIEW);brush.setAlpha(160);for(int y=0;y<pending.length;y++)for(int x=0;x<pending[y].length();x++)if(pending[y].charAt(x)=='O'&&engine.valid(pointerX-w/2+x,pointerY-pending.length/2+y)){float px=ox+(pointerX-w/2+x)*scale,py=oy+(pointerY-pending.length/2+y)*scale;c.drawRect(px+inset,py+inset,px+scale-inset,py+scale-inset,brush);}brush.setAlpha(255);brush.setStyle(Paint.Style.STROKE);c.drawRect(ox+(pointerX-w/2)*scale,oy+(pointerY-pending.length/2)*scale,ox+(pointerX-w/2+w)*scale,oy+(pointerY-pending.length/2+pending.length)*scale,brush);brush.setStyle(Paint.Style.FILL);}if(engine.borders){brush.setColor(MUTED);brush.setStyle(Paint.Style.STROKE);c.drawRect(ox,oy,ox+engine.cols*scale,oy+engine.rows*scale,brush);brush.setStyle(Paint.Style.FILL);}if(keyboardCursor){brush.setColor(CURSOR);brush.setStrokeWidth(dp(2));brush.setStyle(Paint.Style.STROKE);c.drawRect(ox+engine.cursorX*scale+1,oy+engine.cursorY*scale+1,ox+(engine.cursorX+1)*scale-1,oy+(engine.cursorY+1)*scale-1,brush);brush.setStyle(Paint.Style.FILL);}}
        void paint(float x,float y){int cx=(int)Math.floor((x-ox)/scale),cy=(int)Math.floor((y-oy)/scale);if(!hasLast){lastCX=cx;lastCY=cy;}int steps=Math.max(1,Math.max(Math.abs(cx-lastCX),Math.abs(cy-lastCY)));for(int i=0;i<=steps;i++)engine.set(Math.round(lastCX+(cx-lastCX)*i/(float)steps),Math.round(lastCY+(cy-lastCY)*i/(float)steps),!tool.equals("Erase"));lastCX=cx;lastCY=cy;hasLast=true;refresh();}
        void navigate(int dx,int dy,boolean select){engine.moveCursor(dx,dy,select);keyboardCursor=true;float x=ox+(engine.cursorX+.5f)*scale,y=oy+(engine.cursorY+.5f)*scale;if(x<scale||x>getWidth()-scale)ox+=getWidth()/2f-x;if(y<scale||y>getHeight()-scale)oy+=getHeight()/2f-y;message=select?"Selected "+engine.selection().size()+" cells.":"Cell "+(engine.cursorX+1)+", "+(engine.cursorY+1)+".";refresh();}
        void select(float x,float y){int cx=(int)Math.floor((x-ox)/scale),cy=(int)Math.floor((y-oy)/scale);if(!engine.valid(cx,cy))return;if(!hasLast){lastCX=cx;lastCY=cy;}int steps=Math.max(1,Math.max(Math.abs(cx-lastCX),Math.abs(cy-lastCY)));for(int i=0;i<=steps;i++)engine.select(Math.round(lastCX+(cx-lastCX)*i/(float)steps),Math.round(lastCY+(cy-lastCY)*i/(float)steps));lastCX=cx;lastCY=cy;hasLast=true;keyboardCursor=true;message="Selected "+engine.selection().size()+" cells.";refresh();}
        @Override public boolean performClick(){super.performClick();return true;}
        public boolean onTouchEvent(android.view.MotionEvent e){pinch.onTouchEvent(e);int action=e.getActionMasked();if(action==MotionEvent.ACTION_DOWN){requestFocus();lastX=e.getX();lastY=e.getY();hasLast=false;multiple=false;placed=false;panning=pan||(e.getMetaState()&KeyEvent.META_ALT_ON)!=0;selecting=(e.getMetaState()&KeyEvent.META_SHIFT_ON)!=0;if(pending!=null&&!panning){pointer(e.getX(),e.getY());pause();engine.place(pending,pointerX,pointerY);pending=null;placed=true;refresh();persist();return true;}if(selecting)select(e.getX(),e.getY());else if(!panning){engine.unselect();pause();engine.checkpoint();paint(e.getX(),e.getY());}return true;}if(action==MotionEvent.ACTION_POINTER_DOWN){multiple=true;if(!panning&&!selecting){engine.undo();refresh();}return true;}if(action==MotionEvent.ACTION_MOVE){if(placed)return true;if(multiple||pinch.isInProgress())return true;if(selecting)select(e.getX(),e.getY());else if(panning){ox+=e.getX()-lastX;oy+=e.getY()-lastY;invalidate();}else paint(e.getX(),e.getY());lastX=e.getX();lastY=e.getY();return true;}if(action==MotionEvent.ACTION_UP||action==MotionEvent.ACTION_CANCEL){performClick();hasLast=false;if(engine.generation==0)engine.rememberSeed();persist();refresh();return true;}return true;}
        public boolean onGenericMotionEvent(android.view.MotionEvent e){if(e.getAction()==MotionEvent.ACTION_HOVER_MOVE){pointer(e.getX(),e.getY());return true;}if(e.getAction()==MotionEvent.ACTION_SCROLL){zoomBy((float)Math.pow(1.15,e.getAxisValue(MotionEvent.AXIS_VSCROLL)),e.getX(),e.getY());return true;}return super.onGenericMotionEvent(e);}
    }
}
