using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
namespace Nithi.Life;
public readonly record struct Cell(int X,int Y);
public record Snapshot(byte[] Cells,long Generation,string Name,byte[]? Initial=null,HashSet<Cell>? Outside=null,HashSet<Cell>? InitialOutside=null,int Cols=160,int Rows=100,bool Borders=false,int Low=2,int High=3,int Birth=3,int[]? PopulationHistory=null);
public sealed class LifeDocument {
 [JsonPropertyName("population_history")] public int[]? PopulationHistory{get;set;}
 public int Version{get;set;}=3;public string App{get;set;}="Conway’s Game of Life Lab";
 public int Rows{get;set;}public int Cols{get;set;}public int[][] Grid{get;set;}=[];
 [JsonPropertyName("generation_zero_grid")] public int[][]? GenerationZeroGrid{get;set;}
 public long Generation{get;set;}public bool Wrap{get;set;}=true;public double Speed{get;set;}=2;public string Name{get;set;}="Imported canvas";
 public bool? Borders{get;set;}[JsonPropertyName("native_cols")]public int? NativeCols{get;set;}[JsonPropertyName("native_rows")]public int? NativeRows{get;set;}
 [JsonPropertyName("live_cells")]public int[][]? LiveCells{get;set;}[JsonPropertyName("generation_zero_cells")]public int[][]? InitialCells{get;set;}
 public Dictionary<string,int>? Rules{get;set;}[JsonPropertyName("v2_compatible")] public bool V2Compatible{get;set;}=true;
}
public sealed class LifeEngine {
 public int Cols=160,Rows=100;public byte[] Cells=new byte[16000];public long Generation;public bool Wrap=true,Borders=false,Equilibrium;
 public int SurvivalMin=2,SurvivalMax=3,BirthCount=3;public double Speed=2;public string Name="Default";
 public List<Snapshot> History=[],Redos=[];public int CursorX=80,CursorY=50;public HashSet<int> Selected=[];public HashSet<Cell> Outside=[],SelectedOutside=[];public Snapshot? Seed;
 public const int PopulationLimit=2048;public List<int> PopulationHistory=[0];
 public int[] PopulationSeries{get{var values=PopulationHistory.ToArray();if(values.Length==0)return [Population];values[^1]=Population;return values;}}
 void ResetPopulation()=>PopulationHistory=[Population];
 void AppendPopulation(){PopulationHistory.Add(Population);if(PopulationHistory.Count>PopulationLimit)PopulationHistory.RemoveAt(0);}
 public int Population=>Cells.Sum(c=>(int)c)+Outside.Count;
 public HashSet<Cell> Live{get{var r=new HashSet<Cell>(Outside);for(int i=0;i<Cells.Length;i++)if(Cells[i]==1)r.Add(new(i%Cols,i/Cols));return r;}}
 public HashSet<Cell> Selection=>Selected.Select(i=>new Cell(i%Cols,i/Cols)).Concat(SelectedOutside).ToHashSet();
 public bool Valid(int x,int y)=>!Borders||(x>=0&&x<Cols&&y>=0&&y<Rows);
 public bool Alive(int x,int y)=>x>=0&&x<Cols&&y>=0&&y<Rows?Cells[y*Cols+x]==1:!Borders&&Outside.Contains(new(x,y));
 public void Unselect(){Selected.Clear();SelectedOutside.Clear();}
 public void Select(int x,int y){if(!Valid(x,y))return;if(x>=0&&x<Cols&&y>=0&&y<Rows)Selected.Add(y*Cols+x);else SelectedOutside.Add(new(x,y));}
 Snapshot Capture()=>new((byte[])Cells.Clone(),Generation,Name,(byte[])(Generation==0?Cells:(Seed?.Cells??Cells)).Clone(),new(Outside),new(Generation==0?Outside:(Seed?.Outside??[])),Cols,Rows,Borders,SurvivalMin,SurvivalMax,BirthCount,PopulationSeries);
 void Restore(Snapshot s){Cols=s.Cols;Rows=s.Rows;Borders=s.Borders;SurvivalMin=s.Low;SurvivalMax=s.High;BirthCount=s.Birth;Cells=(byte[])s.Cells.Clone();Outside=new(s.Outside??[]);Generation=s.Generation;PopulationHistory=s.PopulationHistory?.ToList()??[Population];Seed=new((byte[])(s.Initial??s.Cells).Clone(),0,s.Name,Outside:new(s.InitialOutside??[]));Unselect();Equilibrium=false;}
 public void Checkpoint(){Redos.Clear();History.Add(Capture());if(History.Count>96)History.RemoveAt(0);}
 public void Undo(){if(History.Count==0)return;Redos.Add(Capture());var s=History[^1];History.RemoveAt(History.Count-1);Restore(s);}
 public void Redo(){if(Redos.Count==0)return;History.Add(Capture());var s=Redos[^1];Redos.RemoveAt(Redos.Count-1);Restore(s);}
 public void Back(){int i=History.FindLastIndex(s=>s.Generation<Generation);if(i<0)return;History.RemoveRange(i+1,History.Count-i-1);Undo();}
 public void Set(int x,int y,bool alive){if(!Valid(x,y))return;if(x>=0&&x<Cols&&y>=0&&y<Rows)Cells[y*Cols+x]=(byte)(alive?1:0);else if(alive)Outside.Add(new(x,y));else Outside.Remove(new(x,y));Equilibrium=false;}
 public void MoveCursor(int dx,int dy,bool select){if(select)Select(CursorX,CursorY);CursorX+=dx;CursorY+=dy;if(Borders){CursorX=Math.Clamp(CursorX,0,Cols-1);CursorY=Math.Clamp(CursorY,0,Rows-1);}if(select)Select(CursorX,CursorY);}
 public void EditSelection(int mode){Checkpoint();var points=Selection;if(points.Count==0)points.Add(new(CursorX,CursorY));foreach(var p in points)Set(p.X,p.Y,mode==2?!Alive(p.X,p.Y):mode==1);if(Generation==0)RememberSeed();}
 public string[]? CopiedRows(){var p=Selection;if(p.Count==0)return null;int x0=p.Min(c=>c.X),y0=p.Min(c=>c.Y),w=p.Max(c=>c.X)-x0+1,h=p.Max(c=>c.Y)-y0+1;if((long)w*h>262144)throw new FormatException("Select a smaller region to copy.");return Enumerable.Range(y0,h).Select(y=>new string(Enumerable.Range(x0,w).Select(x=>p.Contains(new(x,y))&&Alive(x,y)?'O':'.').ToArray())).ToArray();}
 public void Place(string[] pattern,int x,int y,bool overwrite=false){if(pattern.Length==0)return;Checkpoint();int w=pattern.Max(r=>r.Length);for(int ry=0;ry<pattern.Length;ry++)for(int rx=0;rx<pattern[ry].Length;rx++)if(pattern[ry][rx]=='O'||overwrite)Set(x-w/2+rx,y-pattern.Length/2+ry,pattern[ry][rx]=='O');if(Generation==0)RememberSeed();}
 public void ConfigureBorders(bool on,int width,int height){if(width<5||width>512||height<5||height>512)throw new FormatException("Width and height must be 5–512.");if(!on&&BirthCount==0)throw new FormatException("Birth at zero neighbors needs a finite canvas.");Checkpoint();var old=Live;Cols=width;Rows=height;Borders=on;Cells=new byte[Cols*Rows];Outside.Clear();Unselect();foreach(var p in old)Set(p.X,p.Y,true);if(on){CursorX=Math.Clamp(CursorX,0,Cols-1);CursorY=Math.Clamp(CursorY,0,Rows-1);}RememberSeed();}
 public void ConfigureRules(int low,int high,int birth){if(low<0||high>8||low>high||birth<0||birth>8||(!Borders&&birth==0))throw new FormatException("Use neighbor counts 0–8, with minimum ≤ maximum. Birth at 0 requires a finite canvas.");Checkpoint();SurvivalMin=low;SurvivalMax=high;BirthCount=birth;Equilibrium=false;}
 public void Step(bool record=true){if(Generation==0)RememberSeed();PopulationHistory=PopulationSeries.ToList();if(record)Checkpoint();var old=Live;var counts=new Dictionary<Cell,int>();foreach(var p in old){counts.TryAdd(p,0);for(int dy=-1;dy<=1;dy++)for(int dx=-1;dx<=1;dx++){if(dx==0&&dy==0)continue;int x=p.X+dx,y=p.Y+dy;if(Borders&&Wrap){x=(x+Cols)%Cols;y=(y+Rows)%Rows;}if(Valid(x,y)){var k=new Cell(x,y);counts[k]=counts.GetValueOrDefault(k)+1;}}}if(Borders&&BirthCount==0)for(int y=0;y<Rows;y++)for(int x=0;x<Cols;x++)counts.TryAdd(new(x,y),0);var next=counts.Where(k=>old.Contains(k.Key)?k.Value>=SurvivalMin&&k.Value<=SurvivalMax:k.Value==BirthCount).Select(k=>k.Key).ToHashSet();Cells=new byte[Cols*Rows];Outside.Clear();foreach(var p in next)Set(p.X,p.Y,true);Equilibrium=old.SetEquals(next);Generation++;AppendPopulation();}
 public void Clear(){Checkpoint();Array.Clear(Cells);Outside.Clear();Unselect();Generation=0;Seed=null;Equilibrium=false;ResetPopulation();}
 public void RememberSeed(){Seed=new((byte[])Cells.Clone(),0,Name,Outside:new(Outside));if(Generation==0)ResetPopulation();}
 public void Restart(){if(Seed is null)return;Checkpoint();Cells=(byte[])Seed.Cells.Clone();Outside=new(Seed.Outside??[]);Generation=0;Equilibrium=false;ResetPopulation();}
 // Used only for engine fixtures and the first demonstration; library clicks use Place.
 public void LoadPattern(Pattern p){Checkpoint();Array.Clear(Cells);Outside.Clear();Generation=0;Name=p.Name;Unselect();int w=p.Rows.Max(r=>r.Length);for(int y=0;y<p.Rows.Length;y++)for(int x=0;x<p.Rows[y].Length;x++)if(p.Rows[y][x]=='O')Set(x+(Cols-w)/2,y+(Rows-p.Rows.Length)/2,true);RememberSeed();}
 public void Randomize(double density=.25)=>RandomizeRegion(density,0,0,Cols,Rows);
 public void RandomizeRegion(double density,int x0,int y0,int w,int h){Checkpoint();Array.Clear(Cells);Outside.Clear();Generation=0;Unselect();for(int y=y0;y<y0+h;y++)for(int x=x0;x<x0+w;x++)Set(x,y,Random.Shared.NextDouble()<density);RememberSeed();}
 public static readonly JsonSerializerOptions JsonOptions=new(){PropertyNamingPolicy=JsonNamingPolicy.CamelCase,PropertyNameCaseInsensitive=true,WriteIndented=true};
 HashSet<Cell> InitialLive(){var r=new HashSet<Cell>(Generation==0?Outside:(Seed?.Outside??Outside));var c=Generation==0?Cells:(Seed?.Cells??Cells);for(int i=0;i<c.Length;i++)if(c[i]==1)r.Add(new(i%Cols,i/Cols));return r;}
 public LifeDocument Document(){var live=Live;var initial=InitialLive();var union=live.Concat(initial).ToArray();int x0=0,y0=0,w=Cols,h=Rows;if(!Borders){x0=union.Length==0?0:union.Min(c=>c.X);y0=union.Length==0?0:union.Min(c=>c.Y);w=Math.Max(5,union.Length==0?5:union.Max(c=>c.X)-x0+1);h=Math.Max(5,union.Length==0?5:union.Max(c=>c.Y)-y0+1);}bool compatible=w<=100&&h<=100;w=Math.Min(512,w);h=Math.Min(512,h);int[][] Grid(HashSet<Cell> p)=>Enumerable.Range(y0,h).Select(y=>Enumerable.Range(x0,w).Select(x=>p.Contains(new(x,y))?1:0).ToArray()).ToArray();return new(){Rows=h,Cols=w,NativeCols=Cols,NativeRows=Rows,Grid=Grid(live),GenerationZeroGrid=Grid(initial),LiveCells=live.OrderBy(p=>p.Y).ThenBy(p=>p.X).Select(p=>new[]{p.X,p.Y}).ToArray(),InitialCells=initial.OrderBy(p=>p.Y).ThenBy(p=>p.X).Select(p=>new[]{p.X,p.Y}).ToArray(),Generation=Generation,Wrap=Wrap,Borders=Borders,Speed=Speed,Name=Name,Rules=new(){["survival_min"]=SurvivalMin,["survival_max"]=SurvivalMax,["birth_count"]=BirthCount},V2Compatible=compatible,PopulationHistory=PopulationSeries};}
 public string Save()=>JsonSerializer.Serialize(Document(),JsonOptions);
 public void Load(string text){if(text.Length>16000000)throw new FormatException("Choose a Life file smaller than 16 MB.");var d=JsonSerializer.Deserialize<LifeDocument>(text,JsonOptions)??throw new FormatException("Empty canvas file.");if(d.Rows<4||d.Rows>512||d.Cols<4||d.Cols>512||d.Grid.Length!=d.Rows||d.Grid.Any(r=>r is null||r.Length!=d.Cols||r.Any(v=>v!=0&&v!=1))||(d.GenerationZeroGrid is not null&&(d.GenerationZeroGrid.Length!=d.Rows||d.GenerationZeroGrid.Any(r=>r is null||r.Length!=d.Cols||r.Any(v=>v!=0&&v!=1))))||d.Generation<0||d.Generation==long.MaxValue||!double.IsFinite(d.Speed)||d.Speed<.1||d.Speed>60)throw new FormatException("Invalid canvas dimensions or data.");int cols=d.NativeCols??d.Cols,rows=d.NativeRows??d.Rows,low=d.Rules?.GetValueOrDefault("survival_min",2)??2,high=d.Rules?.GetValueOrDefault("survival_max",3)??3,birth=d.Rules?.GetValueOrDefault("birth_count",3)??3;bool borders=d.Borders??true;void Validate(int[][]? points){if(points!=null&&(points.Length>1000000||points.Any(p=>p.Length!=2||p.Any(c=>c < -1000000000||c>1000000000))))throw new FormatException("Invalid infinite coordinates.");}Validate(d.LiveCells);Validate(d.InitialCells);if(cols<4||cols>512||rows<4||rows>512||low<0||high>8||low>high||birth<0||birth>8||(!borders&&birth==0))throw new FormatException("Invalid rules or boundaries.");var fresh=new LifeEngine{Cols=cols,Rows=rows,Cells=new byte[cols*rows],Borders=borders,Wrap=d.Wrap,Speed=d.Speed,Name=d.Name,SurvivalMin=low,SurvivalMax=high,BirthCount=birth,Generation=d.Generation,CursorX=cols/2,CursorY=rows/2};if(d.LiveCells!=null){foreach(var p in d.LiveCells)fresh.Set(p[0],p[1],true);}else for(int y=0;y<d.Rows;y++)for(int x=0;x<d.Cols;x++)fresh.Set(x,y,d.Grid[y][x]==1);var initial=new LifeEngine{Cols=cols,Rows=rows,Cells=new byte[cols*rows],Borders=borders};if(d.InitialCells!=null){foreach(var p in d.InitialCells)initial.Set(p[0],p[1],true);}else for(int y=0;y<d.Rows;y++)for(int x=0;x<d.Cols;x++)initial.Set(x,y,(d.GenerationZeroGrid??d.Grid)[y][x]==1);Cols=cols;Rows=rows;Cells=fresh.Cells;Outside=fresh.Outside;Borders=borders;Wrap=d.Wrap;Speed=d.Speed;Name=d.Name;Generation=d.Generation;SurvivalMin=low;SurvivalMax=high;BirthCount=birth;PopulationHistory=(d.PopulationHistory??[]).TakeLast(PopulationLimit).ToList();if(PopulationHistory.Any(v=>v<0))PopulationHistory.Clear();PopulationHistory=PopulationSeries.ToList();History.Clear();Redos.Clear();Unselect();CursorX=cols/2;CursorY=rows/2;Equilibrium=false;Seed=new(initial.Cells,0,Name,Outside:initial.Outside);}
 public bool MatchesSaved(string saved){try{var current=System.Text.Json.Nodes.JsonNode.Parse(Save())!.AsObject();var previous=System.Text.Json.Nodes.JsonNode.Parse(saved)!.AsObject();if(previous["population_history"] is null)current.Remove("population_history");return System.Text.Json.Nodes.JsonNode.DeepEquals(current,previous);}catch{return false;}}

}
